USE [_MORPHEUS_ENGINE_]
GO

-- ESTA VIEW CONCENTRA OS DADOS PROFISSIONAIS DE CADA UTILIZADOR;
CREATE VIEW VW_USER_PROFESSIONAL_CARACTERISTICS AS (SELECT USER_ID,
USER_FIRST_NAME,
 USER_LAST_NAME,
 USER_PASSWORD_HASH,
 USER_EMAIL,
 USER_PHONENUMBER,
 USER_PROFILE_PICTURE_PATH,
 USER_REGISTRATION_TIMESTAMP,
 USER_BIRTHDATE,
 USER_GENDERS.USER_GENDER_NAME,
 COUNTRIES.COUNTRY_NAME,
 COUNTRIES.COUNTRY_CAPITAL_CITY,
 USER_ADRESS,
 USER_CITIZEN_CARD_NUMBER,
 USER_SALARY,
 USER_BANK_ACCOUNT_NUMBER,
 USER_ACADEMIC_LEVEL.USER_ACADEMIC_LEVEL_NAME,
 USER_JOBS.USER_JOB_NAME,
 USER_LEVEL.USER_LEVEL_NAME
 FROM USERS (NOLOCK)
 INNER JOIN USER_GENDERS ON USER_GENDERS.USER_GENDER_ID = USERS.USER_GENDER_ID 
 INNER JOIN COUNTRIES ON USERS.USER_COUNTRY_ID = COUNTRIES.COUNTRY_ID
 INNER JOIN USER_ACADEMIC_LEVEL ON USER_ACADEMIC_LEVEL.USER_ACADEMIC_LEVEL_ID = USERS.USER_ACADEMIC_LEVEL_ID
 INNER JOIN USER_JOBS ON USER_JOBS.USER_JOB_ID = USERS.USER_JOB_ID
 INNER JOIN USER_LEVEL ON USERS.USER_LEVEL_ID = USER_LEVEL.USER_LEVEL_ID);
GO

--ESTE SELECT LISTA OS DADOS PROFISSIONAIS DE CADA UTILIZADOR (DA VIEW 'VW_USER_PROFESSIONAL_CARACTERISTICS') ORDENADOS PELA DATA DE NASCIMENTO ASCENDENTEMENTE;
SELECT * FROM VW_USER_PROFESSIONAL_CARACTERISTICS ORDER BY USER_BIRTHDATE ASC;
GO

--ESTA VIEW CONCENTRA OS DADOS DE CADA VEÍCULO;
CREATE VIEW VW_SCIENTIFIC_PROSPECTION_DATA AS (SELECT TASK_ID,
TASK_TIMESTAMP,
TASK_LOCATION,
TASK_RAW_DATA,
VEHICLES.VEHICLE_SERIAL_NUMBER,
VEHICLES.VEHICLE_NAME,
VEHICLE_TYPES.VEHICLE_TYPE_NAME,
SCIENTIFIC_TASK_TYPES.TASK_TYPE_NAME,
TASK_EVENTS.TASK_EVENT_NAME
FROM SCIENTIFIC_PROSPECTION_LOGS (NOLOCK)
INNER JOIN VEHICLES ON VEHICLES.VEHICLE_ID = SCIENTIFIC_PROSPECTION_LOGS.TASK_DEVICE_ID 
INNER JOIN VEHICLE_TYPES ON VEHICLE_TYPES.VEHICLE_TYPE_ID = VEHICLES.VEHICLE_TYPE_ID
INNER JOIN TASK_EVENTS ON TASK_EVENTS.TASK_EVENT_ID = SCIENTIFIC_PROSPECTION_LOGS.TASK_EVENT_ID
INNER JOIN SCIENTIFIC_TASK_TYPES ON SCIENTIFIC_TASK_TYPES.TASK_TYPE_NAME = SCIENTIFIC_PROSPECTION_LOGS.TASK_TYPE_ID);
GO

--ESTE SELECT LISTA OS DADOS DE CADA VEÍCULO (DA VIEW 'VW_SCIENTIFIC_PROSPECTION_DATA') ONDE O 'TASK_TYPE_NAME' É 'Atmospheric Research' E O 'VEHICLE_NAME' COMECA PELA LETRA 'A';
SELECT * FROM VW_SCIENTIFIC_PROSPECTION_DATA WHERE TASK_TYPE_NAME = 'Atmospheric Research' AND VEHICLE_NAME LIKE ('A%');
GO

--ESTA VIEW CONCETRA OS DADOS DE CADA MÁQUINA;
CREATE VIEW MACHINES AS (SELECT POWER_STORAGE_DEVICES.POWER_STORAGE_DEVICE_NAME,
POWER_PLANTS.POWER_PLANT_NAME,
LIFE_SUPPORT_SYSTEMS.SYSTEM_NAME,
MACHINE_STATUS_NAME
FROM MACHINE_STATUS (NOLOCK)
INNER JOIN POWER_STORAGE_DEVICES ON POWER_STORAGE_DEVICES.POWER_STORAGE_DEVICE_STATUS_ID = MACHINE_STATUS.MACHINE_STATUS_ID
INNER JOIN POWER_PLANTS ON POWER_PLANTS.POWER_PLANT_STATUS_ID = MACHINE_STATUS.MACHINE_STATUS_ID
INNER JOIN LIFE_SUPPORT_SYSTEMS ON LIFE_SUPPORT_SYSTEMS.SYSTEM_STATUS_ID = MACHINE_STATUS.MACHINE_STATUS_ID);
GO

--ESTE SELECT CONTÉM OS DADOS DE CADA MÁQUINA (DA VIEW 'MACHINES') ORDENADA PELO 'MACHINE_STATUS_NAME' DESCENDENTEMENTE, SENDO SOMENTE LISTADO O PRIMEIRO REGISTO;
SELECT TOP 1 * FROM MACHINES ORDER BY MACHINE_STATUS_NAME DESC;
GO