USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

-- É SELECIONADO AS CARACTERÍSTICAS DO ARRANHA-CÉUS MAIS ALTO DE TODAS AS CIDADES.
SELECT TOP (1) CITIES.CITY_NAME, * FROM CITY_BUILDINGS (NOLOCK) 
INNER JOIN CITIES ON CITY_BUILDINGS.BUILDING_CITY_ID = CITIES.CITY_ID 
ORDER BY BUILDING_HEIGHT DESC;
GO

--É SELECIONADA A EMPRESA QUE MAIS INVESTE EM CONSTRUÇÃO MARCIANA.
SELECT TOP (1) COMPANY_NAME FROM COMPANIES (NOLOCK) 
INNER JOIN CONSTRUCTION_LOGS (NOLOCK) ON COMPANIES.COMPANY_ID = CONSTRUCTION_COMPANY_ID 
GROUP BY COMPANY_NAME ORDER BY COUNT(CONSTRUCTION_COMPANY_ID) DESC;
GO

--SÃO SELECIONADOS OS EDIFÍCIOS QUE SE ENCONTRAM EM CONSTRUÇÃO.
SELECT BUILDING_NAME, BUILDING_LOCATION, CITY_BUILDING_TYPES.CITY_BUILDING_TYPE_NAME, CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_NAME FROM CITY_BUILDINGS
(NOLOCK) INNER JOIN CITY_BUILDING_TYPES (NOLOCK) ON CITY_BUILDINGS.BUILDING_TYPE_ID = CITY_BUILDING_TYPES.CITY_BUILDING_TYPE_ID
INNER JOIN CONSTRUCTION_STATUS (NOLOCK) ON CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_ID = CITY_BUILDINGS.BUILDING_CONSTRUCTION_STATUS_ID
WHERE CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_NAME = 'ONGOING';
GO