--======================================================================================================================================================
--============================= BUILDING_QUERIES.sql ====================================================================================================
--============================= Contem queries para obter informacoes sobre edificios e construções. ========================
--======================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

-- SÃO SELECIONADAS AS CARACTERÍSTICAS DO ARRANHA-CÉUS MAIS ALTO DE TODAS AS CIDADES.
SELECT TOP(1) BUILDING_ID,
CITY_BUILDING_TYPE_NAME,
BUILDING_NAME,
BUILDING_LOCATION,
BUILDING_HEIGHT,
BUILDING_WIDTH,
BUILDING_LENGTH,
BUILDING_POWER_CONSUMPTION,
BUILDING_CONSTRUCTION_DATE,
BUILDING_PLANT,
BUILDING_OWNER_FIRST_NAME + ' ' + BUILDING_OWNER_LAST_NAME AS BUILDING_OWNER_FULL_NAME,
CONSTRUCTION_STATUS_NAME,
BUILDING_COST,
BUILDING_CITY_ID,
CITY_NAME,
CITY_PRESIDENT_FIRST_NAME + ' ' + CITY_PRESIDENT_LAST_NAME AS CITY_PRESIDENT_FULL_NAME
FROM VW_BUILDINGS_FULL_INFORMATION (NOLOCK)
ORDER BY BUILDING_HEIGHT DESC;
GO

--É SELECIONADA A EMPRESA QUE MAIS INVESTE EM CONSTRUÇÃO MARCIANA.
SELECT TOP (1) COMPANY_NAME FROM COMPANIES (NOLOCK) 
INNER JOIN CONSTRUCTION_LOGS (NOLOCK) ON COMPANIES.COMPANY_ID = CONSTRUCTION_COMPANY_ID 
GROUP BY COMPANY_NAME ORDER BY COUNT(CONSTRUCTION_COMPANY_ID) DESC;
GO

--SÃO SELECIONADOS OS EDIFÍCIOS QUE SE ENCONTRAM EM CONSTRUÇÃO.
SELECT BUILDING_NAME, BUILDING_LOCATION, CITY_BUILDING_TYPES.CITY_BUILDING_TYPE_NAME, CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_NAME FROM CITY_BUILDINGS
(NOLOCK) INNER JOIN CITY_BUILDING_TYPES (NOLOCK) ON CITY_BUILDINGS.BUILDING_TYPE_ID = CITY_BUILDING_TYPES.CITY_BUILDING_TYPE_ID
INNER JOIN CONSTRUCTION_STATUS (NOLOCK) ON CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_ID = CITY_BUILDINGS.BUILDING_CONSTRUCTION_STATUS_ID
WHERE CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_NAME = 'ONGOING';
GO