USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--CIDADES
--ESTE SELECT CALCULA A TAXA DE DESPERDICIO DE ENERGIA DE CADA CENTRAL, ORDENANDO OS VALORES POR ORDEM CRESCENTE DE TAXA DE DESPERDÍCIO.
WITH SUBQUERY1 AS (SELECT POWER_PLANT_ID, 
CONVERT(int, dbo.FN_CLAMP_FLOAT(CONVERT(float, dbo.FN_CALC_WASTED_ENERGY(dbo.FN_ENERGY_PRODUCTION_LAST_MONTH(POWER_PLANT_ID, MONTH(GETDATE())), 
dbo.FN_ENERGY_CONSUMPTION_LAST_MONTH(POWER_PLANT_ID, MONTH(GETDATE())), 
dbo.FN_ENERGY_STORAGE_LAST_MONTH(POWER_PLANT_ID, MONTH(GETDATE())))), 0, 1000000000)) AS WASTED_ENERGY 
FROM VW_POWER_FLUX_LOGS),
SUBQUERY2 AS (SELECT SUBQUERY1.POWER_PLANT_ID, 
dbo.FN_CALC_PERCENTAGE(dbo.FN_ENERGY_PRODUCTION_LAST_MONTH(SUBQUERY1.POWER_PLANT_ID, MONTH(GETDATE())), SUBQUERY1.WASTED_ENERGY) 
AS WASTED_ENERGY_RATE FROM SUBQUERY1)
SELECT SUBQUERY2.POWER_PLANT_ID, SUBQUERY2.WASTED_ENERGY_RATE FROM SUBQUERY2

--SÃO SELECIONADAS AS CIDADES AS CIDADES COM MENOR CUSTO DE VIDA.
SELECT TOP (20) * FROM VW_CITIES (NOLOCK) RIGHT JOIN VW_CITIES_ECONOMICAL_DATA 
(NOLOCK) ON VW_CITIES.CITY_ID = VW_CITIES_ECONOMICAL_DATA.CITY_ID 
WHERE (VW_CITIES_ECONOMICAL_DATA.CITY_AVERAGE_INCOME - VW_CITIES_ECONOMICAL_DATA.CITY_LIFE_COST) > 0 
ORDER BY VW_CITIES_ECONOMICAL_DATA.CITY_GDP DESC;
GO

--É SELECIONADA A CIDADE MAIS SAUDÁVEL, TENDO EM CONTA OS DADOS AMBIENTAIS.
SELECT TOP (1) * FROM VW_CITIES (NOLOCK) RIGHT JOIN CITY_ENVIRONMENTAL_DATA (NOLOCK) 
ON VW_CITIES.CITY_ID = CITY_ENVIRONMENTAL_DATA.CITY_ID WHERE (CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_TEMPERATURE - 26) <= 5 
AND (CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_HUMIDITY - 50) <= 15 ORDER BY CITY_ENVIRONMENTAL_DATA.CITY_OXYGEN_LEVELS DESC;
GO

--É SELECIONADA A CIDADE MENOS SAUDÁVEL, TENDO EM CONTA OS DADOS AMBIENTAIS.
SELECT TOP (1) * FROM VW_CITIES (NOLOCK) RIGHT JOIN CITY_ENVIRONMENTAL_DATA (NOLOCK) 
ON VW_CITIES.CITY_ID = CITY_ENVIRONMENTAL_DATA.CITY_ID WHERE (CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_TEMPERATURE - 26) > 5 
AND (CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_HUMIDITY - 50) > 15 ORDER BY CITY_ENVIRONMENTAL_DATA.CITY_OXYGEN_LEVELS ASC;
GO

--É OBTIDO A TAXA DE CRIMINALIDADE DE TODAS AS CIDADE DE MARTE.
WITH SUBQUERY2 AS (SELECT SUM(CITY_DEMOGRAPHICS_DATA.CITY_CRIME_RATE) AS CITY_CRIME_RATE FROM CITY_DEMOGRAPHICS_DATA (NOLOCK)),
SUBQUERY3 AS (SELECT (COUNT(CITY_DEMOGRAPHICS_DATA.CITY_ID)*100) AS CITY_CRIME_RATE2 FROM CITY_DEMOGRAPHICS_DATA (NOLOCK)),
SUBQUERY4 AS (SELECT dbo.FN_CALC_PERCENTAGE(SUBQUERY3.CITY_CRIME_RATE2, (SUBQUERY2.CITY_CRIME_RATE)) AS MARS_CRIME_RATE FROM SUBQUERY2, SUBQUERY3)
SELECT (CAST(SUBQUERY4.MARS_CRIME_RATE AS VARCHAR) + ' %') AS MARS_CRIME_RATE FROM SUBQUERY4;
GO

--É SELECIONADO O NÚMERO DE PESSOAS POR METRO QUADRADO AGRUPADO POR CIDADE.
SELECT CITY_NAME, (CITY_POPULATION/CITY_SURFACE_AREA) AS PEOPLE_PER_SQUARE_METER FROM VW_CITIES_DEMOGRAPHIC_DATA (NOLOCK) GROUP BY CITY_NAME, CITY_POPULATION, CITY_SURFACE_AREA ORDER BY (CITY_POPULATION/CITY_SURFACE_AREA) ASC;SELECT CITY_NAME, (CITY_POPULATION/CITY_SURFACE_AREA) AS PEOPLE_PER_SQUARE_METER FROM VW_CITIES_DEMOGRAPHIC_DATA 
(NOLOCK) GROUP BY CITY_NAME, CITY_POPULATION, CITY_SURFACE_AREA ORDER BY (CITY_POPULATION/CITY_SURFACE_AREA) ASC;
GO

--SÃO SELECIONADAS AS CIDADES QUE SE ENCONTRAM EM CONSTRUÇÃO.
SELECT CITY_NAME, CITY_LOCATION, CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_NAME FROM CITIES 
(NOLOCK) INNER JOIN CONSTRUCTION_STATUS (NOLOCK) ON CITIES.CITY_CONSTRUCTION_STATUS_ID = CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_ID 
