--==================================================================================================================
--============= USER_QUERIES.sql ===================================================================================
--============= Contem queries para listagem e analise estatistica de dados inerentes ás empresas ==================
--==================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--#region LIST_QUERIES
    --QUERY PARA LISTAR A INFORMAÇÃO BASICA DAS 5 EMPRESAS MAIS VALIOSAS REGISTADAS
    SELECT TOP(5) * FROM VW_COMPANY_DATA (NOLOCK) ORDER BY COMPANY_CAPITAL DESC;

    --QUERY PARA LISTAR A INFORMAÇÃO BASICA DAS EMPRESAS CLASSIFICADAS COMO UNICORNIOS (VALORIZADAS EM MASI DE 1 MILHAR DE MILHÃO DE DOLARES)
    SELECT * FROM VW_COMPANY_DATA (NOLOCK) WHERE COMPANY_CAPITAL > 1000000000;

    --EXECUÇÃO DE PROCEDURES QUE LISTAM AS EMPRESAS DE UM DETERMINADO TIPO
    EXEC SP_FILTER_COMPANY_BY_TYPE @COMPANY_TYPE_NAME = 'Energy';
    EXEC SP_FILTER_COMPANY_BY_TYPE @COMPANY_TYPE_NAME = 'Tech';
    EXEC SP_FILTER_COMPANY_BY_TYPE @COMPANY_TYPE_NAME = 'Construction';
    EXEC SP_FILTER_COMPANY_BY_TYPE @COMPANY_TYPE_NAME = 'Finance';
    EXEC SP_FILTER_COMPANY_BY_TYPE @COMPANY_TYPE_NAME = 'Healthcare';
    EXEC SP_FILTER_COMPANY_BY_TYPE @COMPANY_TYPE_NAME = 'Logistics';
    EXEC SP_FILTER_COMPANY_BY_TYPE @COMPANY_TYPE_NAME = 'Manufacturing';
    EXEC SP_FILTER_COMPANY_BY_TYPE @COMPANY_TYPE_NAME = 'Consulting';
    EXEC SP_FILTER_COMPANY_BY_TYPE @COMPANY_TYPE_NAME = 'Retail';
    EXEC SP_FILTER_COMPANY_BY_TYPE @COMPANY_TYPE_NAME = 'Services';

    --EXECUÇÃO DE PROCEDURES QUE LISTAM AS EMPRESAS DE UM DETERMINADO PAÍS
    EXEC SP_FILTER_COMPANIES_BY_COUNTRY @COUNTRY_NAME = 'Country A';

    --EXECUÇÃO DE PROCEDURES QUE LISTAM OS UTILIZADORES QUE TRABALHAM NUMA DETERMINADA EMPRESA
    EXEC SP_FILTER_USERS_BY_COMPANY @COMPANY_NAME = 'EnergyOne';
    EXEC SP_FILTER_USERS_BY_COMPANY @COMPANY_NAME = 'TechNova';
    EXEC SP_FILTER_USERS_BY_COMPANY @COMPANY_NAME = 'ConstructCo';
    EXEC SP_FILTER_USERS_BY_COMPANY @COMPANY_NAME = 'FinancePlus';
    EXEC SP_FILTER_USERS_BY_COMPANY @COMPANY_NAME = 'HealthCare Inc';
    EXEC SP_FILTER_USERS_BY_COMPANY @COMPANY_NAME = 'LogiTrans';
    EXEC SP_FILTER_USERS_BY_COMPANY @COMPANY_NAME = 'ManuWorks';
    EXEC SP_FILTER_USERS_BY_COMPANY @COMPANY_NAME = 'ConsultCorp';
    EXEC SP_FILTER_USERS_BY_COMPANY @COMPANY_NAME = 'RetailMart';
    EXEC SP_FILTER_USERS_BY_COMPANY @COMPANY_NAME = 'ServiceHub';

    SELECT VW_USERS_FULL_INFORMATION.USER_FIRST_NAME, VW_USERS_FULL_INFORMATION.USER_LAST_NAME, VW_COMPANY_DATA.COMPANY_NAME, VW_USERS_FULL_INFORMATION.USER_SALARY, VW_USERS_FULL_INFORMATION.USER_JOB_NAME FROM USER_REL_COMPANY (NOLOCK)
    INNER JOIN VW_COMPANY_DATA (NOLOCK) ON VW_COMPANY_DATA.COMPANY_ID = USER_REL_COMPANY.USER_COMPANY_ID
    INNER JOIN VW_USERS_FULL_INFORMATION ON VW_USERS_FULL_INFORMATION.USER_ID = USER_REL_COMPANY.USER_ID
--#endregion LIST_QUERIES

--#region STATISTICAL_QUERIES
    --QUERY PARA CALCULAR A MEDIA SALARIAL DAS EMPRESAS (AS MEDIAS SÃO ORDENADAS DESCENDENTEMENTE)
    SELECT VW_COMPANY_DATA.COMPANY_NAME, AVG(VW_USERS_FULL_INFORMATION.USER_SALARY) AS AVERAGE_SALARY FROM USER_REL_COMPANY (NOLOCK)
    INNER JOIN VW_COMPANY_DATA (NOLOCK) ON VW_COMPANY_DATA.COMPANY_ID = USER_REL_COMPANY.USER_COMPANY_ID
    INNER JOIN VW_USERS_FULL_INFORMATION ON VW_USERS_FULL_INFORMATION.USER_ID = USER_REL_COMPANY.USER_ID
    GROUP BY VW_COMPANY_DATA.COMPANY_NAME
    ORDER BY AVERAGE_SALARY DESC;

    --EXECUÇÃO DE PROCEDURES QUE CALCULAM A MEDIA SALARIAL DOS UTILIZADORES DE UMA DETERMINADA PROFISSÃO, NUMA DETERMINADA EMPRESA (SE FOR ATRIBUIDO O VALOR 'ALL' AO PARÂMETRO @JOB_NAME, ESTE ASSUME TODAS AS PROFISSÕES)
    EXEC SP_CALC_AVERAGE_SALARIES_BY_JOB_AND_COMPANY @COMPANY_NAME = 'ConstructCo', @JOB_NAME = 'Scientist';
    EXEC SP_CALC_AVERAGE_SALARIES_BY_JOB_AND_COMPANY @COMPANY_NAME = 'ConstructCo', @JOB_NAME = 'Technician';
    EXEC SP_CALC_AVERAGE_SALARIES_BY_JOB_AND_COMPANY @COMPANY_NAME = 'ConstructCo', @JOB_NAME = 'ALL';

    --QUERY PARA CALCULAR A PERCENTAGEM DE EMPRESAS UNICORNIOS EM RELAÇÃO AO TOTAL DE EMPRESAS REGISTADAS
    DECLARE @COUNT_USERS INT = (SELECT COUNT(USER_ID) AS TOTAL_USERS FROM VW_USERS_FULL_INFORMATION (NOLOCK))
    SELECT (CAST(dbo.FN_CALC_PERCENTAGE(@COUNT_USERS, COUNT(*)) AS VARCHAR) + '%') AS UNICORN_COMPANIES_PERCENTAGE FROM VW_COMPANY_DATA (NOLOCK) WHERE COMPANY_CAPITAL > 1000000000;
--#endregion STATISTICAL_QUERIES