USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--SÃO SELECIONADOS OS SISTEMAS DE SUPORTE À VIDA QUE ESTÃO ASSOCIADOS A CADA CIDADE E RESPETIVAS CARACTERÍSTICAS.
SELECT CITIES.CITY_NAME,  STRING_AGG(LIFE_SUPPORT_SYSTEMS.SYSTEM_NAME, ', ') AS SYSTEMS_NAME, 
STRING_AGG(LIFE_SUPPORT_SYSTEMS.SYSTEM_MAX_OUTPUT_CAPACITY, ', ') AS SYSTEMS_MAX_OUTPUT_CAPACITY, 
STRING_AGG(LIFE_SUPPORT_SYSTEMS.SYSTEM_LOCATION, ', ') AS SYSTEMS_LOCATION
FROM CITY_REL_LIFE_SUPPORT_SYSTEMS (NOLOCK) INNER JOIN CITIES (NOLOCK)
ON CITY_REL_LIFE_SUPPORT_SYSTEMS.CITY_ID = CITIES.CITY_ID
INNER JOIN LIFE_SUPPORT_SYSTEMS (NOLOCK)
ON CITY_REL_LIFE_SUPPORT_SYSTEMS.CITY_LIFE_SUPPORT_SYSTEM_ID = LIFE_SUPPORT_SYSTEMS.SYSTEM_ID
GROUP BY CITIES.CITY_NAME;
GO

--SÃO SELECIONADOS OS PRODUTOS ALIMENTARES CUJO PAZO DE VALIDADE JÁ EXPIROU.
SELECT FOOD_TYPES.FOOD_TYPE_NAME, LOG_FOOD_PRODUCTION, LOG_FOOD_EXPIRATION_DATE FROM FOOD_PRODUCTION_LOGS 
(NOLOCK) INNER JOIN FOOD_TYPES (NOLOCK) ON FOOD_PRODUCTION_LOGS.LOG_FOOD_TYPE_ID = FOOD_TYPES.FOOD_TYPE_ID
WHERE DATEDIFF(DAY, FOOD_PRODUCTION_LOGS.LOG_FOOD_EXPIRATION_DATE, GETDATE()) > 0;
GO

--SÃO SELECIONADAS AS INFORMAÇÕES DAS MANUTENÇÕES DOS SISTEMAS DE SUPORTE À VIDA QUE JÁ FORAM REALIZADAS.
SELECT LIFE_SUPPORT_SYSTEMS.SYSTEM_NAME, MAINTENANCE_DESCRIPTION, USERS.USER_FIRST_NAME, USERS.USER_LAST_NAME,
MAINTENANCE_RESULTS_INFO, MAINTENANCE_DATE FROM LIFE_SUPPORT_SYSTEM_MAINTENANCE_LOGS(NOLOCK)
INNER JOIN LIFE_SUPPORT_SYSTEMS (NOLOCK) ON LIFE_SUPPORT_SYSTEM_MAINTENANCE_LOGS.SYSTEM_ID = LIFE_SUPPORT_SYSTEMS.SYSTEM_ID
INNER JOIN USERS (NOLOCK) ON LIFE_SUPPORT_SYSTEM_MAINTENANCE_LOGS.MAINTENANCE_TECHNITIAN_ID = USERS.USER_ID
ORDER BY MAINTENANCE_DATE DESC;
GO

--É OBTIDA A O RENDIMENTO DE CADA SISTEMA DE SUPORTE À VIDA DE OXIGÉNIO RELATIVAMENTE À SUA CAPACIDADE MÁXIMA DE PRODUÇÃO.
SELECT LOG_ID, (CAST(ROUND(CAST(LOG_OXIGEN_OUTPUT AS FLOAT) / CAST(LIFE_SUPPORT_SYSTEMS.SYSTEM_MAX_OUTPUT_CAPACITY AS FLOAT)*100, 2) AS VARCHAR) + ' %') AS OXIGEN_OUTPUT_RATE
FROM OXIGEN_PRODUCTION_LOGS (NOLOCK) INNER JOIN LIFE_SUPPORT_SYSTEMS (NOLOCK) ON OXIGEN_PRODUCTION_LOGS.LOG_SOURCE_ID = LIFE_SUPPORT_SYSTEMS.SYSTEM_ID;
GO

--É OBTIDA A O RENDIMENTO DE CADA SISTEMA DE SUPORTE À VIDA DE ÁGUA RELATIVAMENTE À SUA CAPACIDADE MÁXIMA DE PRODUÇÃO.
SELECT LOG_ID, (CAST(ROUND(CAST(LOG_WATER_OUTPUT AS FLOAT) / CAST(LIFE_SUPPORT_SYSTEMS.SYSTEM_MAX_OUTPUT_CAPACITY AS FLOAT)*100, 2) AS VARCHAR) + ' %') AS WATER_OUTPUT_RATE
FROM WATER_EXTRACTION_LOGS (NOLOCK) INNER JOIN LIFE_SUPPORT_SYSTEMS (NOLOCK) ON WATER_EXTRACTION_LOGS.LOG_SOURCE_ID = LIFE_SUPPORT_SYSTEMS.SYSTEM_ID;
GO

