USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--ESTE SELECT LISTA OS DADOS PROFISSIONAIS DE CADA UTILIZADOR (DA VIEW 'VW_USER_PROFESSIONAL_CARACTERISTICS') ORDENADOS PELA DATA DE NASCIMENTO ASCENDENTEMENTE;
SELECT * FROM VW_USER_PROFESSIONAL_CARACTERISTICS ORDER BY USER_BIRTHDATE ASC;
GO

--ESTE SELECT LISTA OS DADOS DE CADA VEÍCULO (DA VIEW 'VW_SCIENTIFIC_PROSPECTION_DATA') ONDE O 'TASK_TYPE_NAME' É 'Atmospheric Research' E O 'VEHICLE_NAME' COMECA PELA LETRA 'A';
SELECT * FROM VW_SCIENTIFIC_PROSPECTION_DATA WHERE TASK_TYPE_NAME = 'Atmospheric Research' AND VEHICLE_NAME LIKE ('A%');
GO

--ESTE SELECT CONTÉM OS DADOS DE CADA MÁQUINA (DA VIEW 'MACHINES') ORDENADA PELO 'MACHINE_STATUS_NAME' DESCENDENTEMENTE, SENDO SOMENTE LISTADO O PRIMEIRO REGISTO;
SELECT TOP 1 * FROM MACHINES ORDER BY MACHINE_STATUS_NAME DESC;
GO