USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--ESTE SELECT LISTA OS DADOS DE CADA UTILIZADOR (DA VIEW 'VW_USER_CARACTERISTICS') ORDENADOS PELA DATA DE NASCIMENTO ASCENDENTEMENTE;
SELECT * FROM VW_USER_CARACTERISTICS (NOLOCK) ORDER BY USER_BIRTHDATE ASC;
GO

--ESTE SELECT LISTA OS DADOS DE CADA VEÍCULO (DA VIEW 'VW_SCIENTIFIC_PROSPECTION_DATA') ONDE O 'TASK_TYPE_NAME' É 'Atmospheric Research' E O 'VEHICLE_NAME' COMECA PELA LETRA 'A';
SELECT * FROM VW_SCIENTIFIC_PROSPECTION_DATA (NOLOCK) WHERE TASK_TYPE_NAME = 'Atmospheric Research' AND VEHICLE_NAME LIKE ('A%');
GO

--ESTE SELECT CONTÉM OS DADOS DE CADA MÁQUINA (DA VIEW 'MACHINES') ORDENADA PELO 'MACHINE_STATUS_NAME' DESCENDENTEMENTE, SENDO SOMENTE LISTADO O PRIMEIRO REGISTO;
SELECT TOP(1) * FROM VEHICLES (NOLOCK) ORDER BY VEHICLE_NAME DESC;
GO

--CITIES
--ESTE SELECT CALCULA A TAXA DE DESPERDICIO DE ENERGIA DE CADA CENTRAL, ORDENANDO OS VALORES POR ORDEM CRESCENTE DE TAXA DE DESPERDÍCIO.
WITH SUBQUERY1 AS (SELECT POWER_PLANT_ID, CONVERT(int, dbo.FN_CLAMP_FLOAT(CONVERT(float, dbo.FN_CALC_WASTED_ENERGY(dbo.FN_ENERGY_PRODUCTION_LAST_MONTH(POWER_PLANT_ID, MONTH(GETDATE())), dbo.FN_ENERGY_CONSUMPTION_LAST_MONTH(POWER_PLANT_ID, MONTH(GETDATE())), dbo.FN_ENERGY_STORAGE_LAST_MONTH(POWER_PLANT_ID, MONTH(GETDATE())))), 0, 1000000000)) AS WASTED_ENERGY FROM VW_POWER_FLUX_LOGS),
SUBQUERY2 AS (SELECT SUBQUERY1.POWER_PLANT_ID, dbo.FN_CALC_PERCENTAGE(dbo.FN_ENERGY_PRODUCTION_LAST_MONTH(SUBQUERY1.POWER_PLANT_ID, MONTH(GETDATE())), SUBQUERY1.WASTED_ENERGY) AS WASTED_ENERGY_RATE FROM SUBQUERY1)
SELECT SUBQUERY2.POWER_PLANT_ID, SUBQUERY2.WASTED_ENERGY_RATE FROM SUBQUERY2

SELECT * FROM VW_SPACE_LOGISTICS