--==================================================================================================================
--============= USER_QUERIES.sql ===================================================================================
--============= Contem queries para listagem e analise estatistica de dados inerentes aos utilizadores =============
--==================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--#region UTILIZADORES

    --#region ROLE_BASED_FILTERING_QUERIES

        /*EXECUÇÃO DE PROCEDURES QUE LISTAM OS UTILIZADORES COM UM DETERMINADO GRAU DE PERMISSÕES.
        LEGENDA:
        ADMINISTRADOR => TÊM DIREITOS TOTAIS DE EDIÇÃO E GESTÃO DA BD;
        PROGRAMADORES =>TÊM DIREITOS RESTRITOS DE EDIÇÃO DA BASE DE DADOS => NÃO TÊM PERMISSÃO PARA ALTERAR AS PERMISSÕES DE OUTROS USERS, NEM PODEM REMOVER A BD;
        ANALISTAS DE DADOS => TÊM DIREITOS TOTAIS DE VISUALIZAÇÃO DE DADOS, EXCETO INFORMAÇÃO SENESIVEL - EX: PASSWORDS;
        UTILIZADORES => TÊM DIREITOS RESTRITOS DE VISUALIZAÇÃO DE DADOS
        */
        EXEC SP_LIST_USERS_BY_PERMISSION_LEVEL @USER_LEVEL_NAME = 'ADMINISTRATOR'
        EXEC SP_LIST_USERS_BY_PERMISSION_LEVEL @USER_LEVEL_NAME = 'DEVELOPERS'
        EXEC SP_LIST_USERS_BY_PERMISSION_LEVEL @USER_LEVEL_NAME = 'DATA_ANALYST'
        EXEC SP_LIST_USERS_BY_PERMISSION_LEVEL @USER_LEVEL_NAME = 'USER'

        --EXECUÇÃO DE PROCEDURES QUE LISTAM OS UTILIZADORES COM UMA DETERMINADA PROFISSÃO.
        EXEC SP_LIST_USERS_BY_JOB @JOB_NAME = 'Engineer';
        EXEC SP_LIST_USERS_BY_JOB @JOB_NAME = 'Technician';
        EXEC SP_LIST_USERS_BY_JOB @JOB_NAME = 'Scientist';
        EXEC SP_LIST_USERS_BY_JOB @JOB_NAME = 'Manager';
        EXEC SP_LIST_USERS_BY_JOB @JOB_NAME = 'Analyst';
        EXEC SP_LIST_USERS_BY_JOB @JOB_NAME = 'Developer';
        EXEC SP_LIST_USERS_BY_JOB @JOB_NAME = 'Administrator';
        EXEC SP_LIST_USERS_BY_JOB @JOB_NAME = 'Supervisor';
        EXEC SP_LIST_USERS_BY_JOB @JOB_NAME = 'Director';
        EXEC SP_LIST_USERS_BY_JOB @JOB_NAME = 'Consultant';

        --QUERY PARA LISTAR OS UTILIZADORES QUE SÃO CEO's
        SELECT DISTINCT USER_FIRST_NAME + ' ' + USER_LAST_NAME AS FULL_NAME, COMPANY_NAME
        FROM VW_COMPANY_DATA (NOLOCK)

        --QUERY PARA LISTAR OS UTILIZADORES COM NIVEL ACADÉMICO SUPERIOR OU IGUAL Á LICENCIATURA (ASSOCIATE DEGREE)
        SELECT USER_ACADEMIC_LEVEL_NAME, USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_PHONENUMBER, USER_PROFILE_PICTURE_PATH, USER_BIRTHDATE, USER_GENDER_NAME, COUNTRY_NAME, USER_ADRESS, USER_JOB_NAME, USER_LEVEL_NAME
        FROM VW_USERS_NON_SENSITIVE_INFORMATION (NOLOCK)
        WHERE USER_ACADEMIC_LEVEL_ID >= 4;

        --QUERY PARA LISTAR OS UTILIZADORES COM NIVEL ACADÉMICO SUPERIOR OU IGUAL AO MESTRADO (MASTER'S DEGREE)
        SELECT USER_ACADEMIC_LEVEL_NAME, USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_PHONENUMBER, USER_PROFILE_PICTURE_PATH, USER_BIRTHDATE, USER_GENDER_NAME, COUNTRY_NAME, USER_ADRESS, USER_JOB_NAME, USER_LEVEL_NAME
        FROM VW_USERS_NON_SENSITIVE_INFORMATION (NOLOCK)
        WHERE USER_ACADEMIC_LEVEL_ID >= 6;

        --QUERY PARA LISTAR A INFORMAÇÃO BASICA DE CADA UTILIZADOR, ORDENADOS PELA DATA DE NASCIMENTO ASCENDENTEMENTE (DO MAIS VELHO PARA O MAIS NOVO)
        SELECT TOP(500)
        USER_ID,
        USER_FIRST_NAME + ' ' + USER_LAST_NAME AS USER_FULL_NAME,
        USER_EMAIL,
        USER_PHONENUMBER,
        USER_PROFILE_PICTURE_PATH,
        USER_BIRTHDATE,
        USER_GENDER_NAME,
        COUNTRY_NAME,
        USER_JOB_NAME
        FROM VW_USERS_BASIC_INFORMATION (NOLOCK)
        ORDER BY USER_BIRTHDATE ASC;

        --EXECUÇÃO DE PROCEDURE QUE LISTA A INFORMAÇÃO BASICA DOS UTILIZADORES DE UM DETERMINADO PAÍS (APENAS UM EXEMPLO ABAIXO)
        EXEC SP_LIST_USERS_BY_COUNTRY @COUNTRY_NAME = 'Country A';

        --EXECUÇÃO DE PROCEDURE QUE CONTABILIZA O NÚMERO DE UTILIZADORES DE UM DETERMINADO PAÍS (APENAS UM EXEMPLO ABAIXO)
        EXEC SP_COUNT_USERS_BY_COUNTRY @COUNTRY_NAME = 'Country A';

        --QUERY PARA LISTAR OS 20 UTILIZADORES MAIS RICOS REGISTADOS.
        SELECT TOP(20) USER_ID, USER_FIRST_NAME + ' ' + USER_LAST_NAME AS USER_FULL_NAME, USER_BIRTHDATE, USER_GENDER_NAME, COUNTRY_NAME, USER_SALARY, USER_ACADEMIC_LEVEL_NAME, USER_JOB_NAME
        FROM VW_USERS_FULL_INFORMATION (NOLOCK)
        ORDER BY USER_SALARY DESC;
    --#endregion ROLE_BASED_FILTERING_QUERIES

    --#region STATISTICAL_QUERIES

        --QUERY PARA CALCULAR A PERCENTAGEM DE UTILIZADORES COM NIVEL ACADÉMICO SUPERIOR OU IGUAL Á LICENCIATURA (ASSOCIATE DEGREE)
        WITH SUBQUERY1 AS (SELECT COUNT(*) AS COUNT_USERS FROM VW_USERS_NON_SENSITIVE_INFORMATION (NOLOCK)),
        SUBQUERY2 AS (SELECT COUNT(*) AS COUNT_USERS_ABOVE_MASTERS FROM VW_USERS_NON_SENSITIVE_INFORMATION (NOLOCK) WHERE USER_ACADEMIC_LEVEL_ID >= 4)
        SELECT CAST(ROUND(dbo.FN_CALC_PERCENTAGE(SUBQUERY1.COUNT_USERS, SUBQUERY2.COUNT_USERS_ABOVE_MASTERS), 2) AS VARCHAR) + ' %' AS USERS_ABOVE_MASTERS_PERCENTAGE
        FROM SUBQUERY1
        FULL JOIN SUBQUERY2 ON 1 = 1;

        --QUERY PARA CALCULAR A PERCENTAGEM DE UTILIZADORES COM NIVEL ACADÉMICO SUPERIOR OU IGUAL AO MESTRADO (MASTER'S DEGREE)
        WITH SUBQUERY1 AS (SELECT COUNT(*) AS COUNT_USERS FROM VW_USERS_NON_SENSITIVE_INFORMATION (NOLOCK)),
        SUBQUERY2 AS (SELECT COUNT(*) AS COUNT_USERS_ABOVE_MASTERS FROM VW_USERS_NON_SENSITIVE_INFORMATION (NOLOCK) WHERE USER_ACADEMIC_LEVEL_ID >= 6)
        SELECT CAST(ROUND(dbo.FN_CALC_PERCENTAGE(SUBQUERY1.COUNT_USERS, SUBQUERY2.COUNT_USERS_ABOVE_MASTERS), 2) AS VARCHAR) + ' %' AS USERS_ABOVE_MASTERS_PERCENTAGE
        FROM SUBQUERY1
        FULL JOIN SUBQUERY2 ON 1 = 1;

        --QUERY PARA CALCULAR A PERCENTAGEM DE UTILIZADORES QUE SÃO CEO's
        WITH SUBQUERY AS (SELECT DISTINCT USER_FIRST_NAME AS USER_FIRST_NAME FROM VW_COMPANY_DATA (NOLOCK)),
        SUBQUERY1 AS (SELECT COUNT(SUBQUERY.USER_FIRST_NAME) AS COUNT_CEO_USERS FROM SUBQUERY),
        SUBQUERY2 AS (SELECT COUNT(*) AS COUNT_TOTAL_USERS FROM VW_USERS_BASIC_INFORMATION (NOLOCK))
        SELECT CAST(ROUND(dbo.FN_CALC_PERCENTAGE(SUBQUERY2.COUNT_TOTAL_USERS, SUBQUERY1.COUNT_CEO_USERS), 2) AS VARCHAR) + ' %' AS CEO_PERCENTAGE
        FROM SUBQUERY1
        FULL JOIN SUBQUERY2 ON 1=1

        --QUERY PARA CALCULAR A DISTRIBUIÇÃO PERCENTUAL DE UTILIZADORES POR GÉNEROS, REGISTADOS NA BASE DE DADOS
        DECLARE @TOTAL_USERS_COUNT INT = (SELECT COUNT(*) AS TOTAL_USERS_COUNT FROM VW_USERS_BASIC_INFORMATION (NOLOCK));
        SELECT USER_GENDER_NAME,
        CAST(ROUND(dbo.FN_CALC_PERCENTAGE(@TOTAL_USERS_COUNT, COUNT(*)), 2) AS VARCHAR) + ' %' AS 'TOTAL_% (ROUNDED)'
        FROM VW_USERS_BASIC_INFORMATION (NOLOCK)
        GROUP BY USER_GENDER_NAME

    --#endregion STATISTICAL_QUERIES
--#endregion UTILIZADORES