USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO
--#region UTILIZADORES
--#region ROLE_BASED_FILTERING_QUERIES
/*EXECUÇÃO DE PROCEDURES QUE LISTAM OS UTILIZADORES COM UM DETERMINADO GRAU DE PERMISSÕES.
LEGENDA:
ADMINISTRADOR => TÊM DIREITOS TOTAIS DE EDIÇÃO E GESTÃO DA BD;
PROGRAMADORES =>TÊM DIREITOS RESTRITOS DE EDIÇÃO DA BASE DE DADOS => NÃO TÊM PERMISSÃO PARA ALTERAR AS PERMISSÕES DE OUTROS USERS, NEM PODEM REMOVER A BD;
ANALISTAS DE DADOS => TÊM DIREITOS TOTAIS DE VISUALIZAÇÃO DE DADOS, EXCETO INFORMAÇÃO SENESIVEL - EX: PASSWORDS;
UTILIZADORES => TÊM DIREITOS RESTRITOS DE VISUALIZAÇÃO DE DADOS
*/
EXEC SP_LIST_USERS_BY_PERMISSION_LEVEL @USER_LEVEL_NAME = 'ADMINISTRATOR'
EXEC SP_LIST_USERS_BY_PERMISSION_LEVEL @USER_LEVEL_NAME = 'DEVELOPERS'
EXEC SP_LIST_USERS_BY_PERMISSION_LEVEL @USER_LEVEL_NAME = 'DATA_ANALYST'
EXEC SP_LIST_USERS_BY_PERMISSION_LEVEL @USER_LEVEL_NAME = 'USER'

--QUERY PARA LISTAR OS UTILIZADORES QUE SÃO CEO's DE ALGUMA EMPRESA
SELECT DISTINCT USER_FIRST_NAME, COMPANY_NAME FROM VW_COMPANY_DATA (NOLOCK)

--QUERY PARA LISTAR OS UTILIZADORES COM NIVEL ACADÉMICO SUPERIOR OU IGUAL AO MESTRADO (MASTER'S DEGREE)
SELECT USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_PHONENUMBER, USER_PROFILE_PICTURE_PATH, USER_BIRTHDATE, USER_GENDER_NAME, COUNTRY_NAME, USER_ADRESS, USER_JOB_NAME, USER_ACADEMIC_LEVEL_NAME, USER_LEVEL_NAME
FROM VW_USER_CARACTERISTICS (NOLOCK) WHERE USER_ACADEMIC_LEVEL_ID >= 6;
--#endregion ROLE_BASED_FILTERING_QUERIES

--#region STATISTICAL_QUERIES
--QUERY PARA CALCULAR A PERCENTAGEM DE UTILIZADORES COM NIVEL ACADÉMICO SUPERIOR OU IGUAL Á LICENCIATURA (ASSOCIATE DEGREE)
WITH SUBQUERY1 AS (SELECT COUNT(*) AS COUNT_USERS FROM VW_USER_CARACTERISTICS),
SUBQUERY2 AS (SELECT COUNT(*) AS COUNT_USERS_ABOVE_MASTERS FROM VW_USER_CARACTERISTICS WHERE USER_ACADEMIC_LEVEL_ID >= 4)
SELECT CAST(ROUND(dbo.FN_CALC_PERCENTAGE(SUBQUERY1.COUNT_USERS, SUBQUERY2.COUNT_USERS_ABOVE_MASTERS), 2) AS VARCHAR) + ' %' AS USERS_ABOVE_MASTERS_PERCENTAGE FROM SUBQUERY1 FULL JOIN SUBQUERY2 ON 1 = 1;
GO

--QUERY PARA CALCULAR A PERCENTAGEM DE UTILIZADORES COM NIVEL ACADÉMICO SUPERIOR OU IGUAL AO MESTRADO (MASTER'S DEGREE)
WITH SUBQUERY1 AS (SELECT COUNT(*) AS COUNT_USERS FROM VW_USER_CARACTERISTICS),
SUBQUERY2 AS (SELECT COUNT(*) AS COUNT_USERS_ABOVE_MASTERS FROM VW_USER_CARACTERISTICS WHERE USER_ACADEMIC_LEVEL_ID >= 6)
SELECT CAST(ROUND(dbo.FN_CALC_PERCENTAGE(SUBQUERY1.COUNT_USERS, SUBQUERY2.COUNT_USERS_ABOVE_MASTERS), 2) AS VARCHAR) + ' %' AS USERS_ABOVE_MASTERS_PERCENTAGE FROM SUBQUERY1 FULL JOIN SUBQUERY2 ON 1 = 1;

--QUERY PARA CALCULAR A PERCENTAGEM DE UTILIZADORES QUE SÃO CEO's DE ALGUMA EMPRESA
WITH SUBQUERY AS (SELECT DISTINCT USER_FIRST_NAME AS USER_FIRST_NAME FROM VW_COMPANY_DATA),
SUBQUERY1 AS (SELECT COUNT(SUBQUERY.USER_FIRST_NAME) AS COUNT_CEO_USERS FROM SUBQUERY),
SUBQUERY2 AS (SELECT COUNT(*) AS COUNT_TOTAL_USERS FROM VW_USER_CARACTERISTICS)
SELECT CAST(ROUND(dbo.FN_CALC_PERCENTAGE(SUBQUERY2.COUNT_TOTAL_USERS, SUBQUERY1.COUNT_CEO_USERS), 2) AS VARCHAR) + ' %' FROM SUBQUERY1 FULL JOIN SUBQUERY2 ON 1=1

--#endregion STATISTICAL_QUERIES

--QUERY PARA LISTAR
--ESTE SELECT LISTA OS DADOS DE CADA UTILIZADOR (DA VIEW 'VW_USER_CARACTERISTICS') ORDENADOS PELA DATA DE NASCIMENTO ASCENDENTEMENTE;
SELECT * FROM VW_USER_CARACTERISTICS (NOLOCK) ORDER BY USER_BIRTHDATE ASC;
--#endregion UTILIZADORES