--==================================================================================================================================================
--============= POWER_MGMT_VIEWS.sql ===============================================================================================================
--============= Aqui são criadas views para a obtenção de estatisticas da produção e distribuição de energia. ======================================
--==================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

CREATE VIEW VW_CITIES AS (SELECT [CITY_ID]
,CITIES.CITY_NAME
,CITIES.CITY_LOCATION
,CITIES.CITY_PRESIDENT_ID
,CITIES.CITY_BUILT_DATE
,CITIES.CITY_CONSTRUCTION_STATUS_ID
,[USER_ID]
,[USER_FIRST_NAME]
,[USER_LAST_NAME]
,[USER_PASSWORD_HASH]
,[USER_EMAIL]
,[USER_PHONENUMBER]
,[USER_PROFILE_PICTURE_PATH]
,[USER_REGISTRATION_TIMESTAMP]
,[USER_BIRTHDATE]
,[USER_GENDER_ID]
,[USER_COUNTRY_ID]
,[USER_ADRESS]
,[USER_CITIZEN_CARD_NUMBER]
,[USER_SALARY]
,[USER_BANK_ACCOUNT_NUMBER]
,[USER_ACADEMIC_LEVEL_ID]
,[USER_JOB_ID]
,[USER_LEVEL_ID]
,CITY_CONSTRUCTION_STATUS.CITY_CONSTRUCTION_STATUS_NAME
FROM CITIES
INNER JOIN USERS ON CITIES.CITY_PRESIDENT_ID = USERS.USER_ID
INNER JOIN CITY_CONSTRUCTION_STATUS ON CITY_CONSTRUCTION_STATUS.CITY_CONSTRUCTION_STATUS_ID = CITIES.CITY_CONSTRUCTION_STATUS_ID)

GO

CREATE VIEW VW_CITIES_ECONOMICAL_DATA AS (SELECT CITY_ECONOMICAL_DATA.CITY_ECONOMICAL_DATA_ID
,CITY_ECONOMICAL_DATA.CITY_ID
,CITY_ECONOMICAL_DATA.CITY_LIFE_COST
,CITY_ECONOMICAL_DATA.CITY_GDP
,CITY_ECONOMICAL_DATA.CITY_AVERAGE_INCOME
,CITIES.CITY_NAME
,CITIES.CITY_LOCATION
,CITIES.CITY_PRESIDENT_ID
,CITIES.CITY_BUILT_DATE
,CITIES.CITY_CONSTRUCTION_STATUS_ID
FROM CITY_ECONOMICAL_DATA
INNER JOIN CITIES ON CITY_ECONOMICAL_DATA.CITY_ID = CITIES.CITY_ID)

GO

CREATE VIEW VW_CITIES_DEMOGRAPHIC_DATA AS (SELECT CITY_DEMOGRAPHICS_DATA.CITY_DEMOGRAPHICS_DATA_ID
,CITY_DEMOGRAPHICS_DATA.CITY_ID
,CITY_DEMOGRAPHICS_DATA.CITY_SURFACE_AREA
,CITY_DEMOGRAPHICS_DATA.CITY_POPULATION
,CITY_DEMOGRAPHICS_DATA.CITY_LIFE_EXPECTANCY
,CITY_DEMOGRAPHICS_DATA.CITY_CRIME_RATE
,CITIES.CITY_NAME
,CITIES.CITY_LOCATION
,CITIES.CITY_PRESIDENT_ID
,CITIES.CITY_BUILT_DATE
,CITIES.CITY_CONSTRUCTION_STATUS_ID
FROM CITY_DEMOGRAPHICS_DATA
INNER JOIN CITIES ON CITY_DEMOGRAPHICS_DATA.CITY_ID = CITIES.CITY_ID)

GO

CREATE VIEW VW_CITIES_ENVIRONMENTAL_DATA AS (SELECT CITY_ENVIRONMENTAL_DATA.CITY_ENVIRONMENTAL_DATA_ID
,CITY_ENVIRONMENTAL_DATA.CITY_ID
,CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_TEMPERATURE
,CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_HUMIDITY
,CITY_ENVIRONMENTAL_DATA.CITY_OXYGEN_LEVELS
,CITIES.CITY_NAME
,CITIES.CITY_LOCATION
,CITIES.CITY_PRESIDENT_ID
,CITIES.CITY_BUILT_DATE
,CITIES.CITY_CONSTRUCTION_STATUS_ID
FROM CITY_ENVIRONMENTAL_DATA
INNER JOIN CITIES ON CITY_ENVIRONMENTAL_DATA.CITY_ID = CITIES.CITY_ID)

GO

CREATE VIEW VW_CITIES_REL_POWERPLANTS AS (SELECT CITY_REL_POWERPLANTS.CITY_REL_POWERPLANT_ID
,CITY_REL_POWERPLANTS.CITY_ID
,CITY_REL_POWERPLANTS.CITY_ENERGY_SOURCE_ID
,CITIES.CITY_NAME
,CITIES.CITY_LOCATION
,CITIES.CITY_PRESIDENT_ID
,CITIES.CITY_BUILT_DATE
,CITIES.CITY_CONSTRUCTION_STATUS_ID
,POWER_PLANTS.POWER_PLANT_NAME
,POWER_PLANTS.POWER_PLANT_COMPANY_ID
,POWER_PLANTS.POWER_PLANT_TYPE_ID
,POWER_PLANTS.POWER_PLANT_LOCATION
,POWER_PLANTS.POWER_PLANT_MAX_OUTPUT_CAPACITY
,POWER_PLANTS.POWER_PLANT_STATUS_ID
,POWER_PLANTS.POWER_PLANT_NEXT_MAINTENANCE_DATE
,POWER_PLANTS.POWER_PLANT_INSTALLATION_DATE
FROM CITY_REL_POWERPLANTS
INNER JOIN CITIES ON CITIES.CITY_ID = CITY_REL_POWERPLANTS.CITY_ID
INNER JOIN POWER_PLANTS ON POWER_PLANTS.POWER_PLANT_ID = CITY_REL_POWERPLANTS.CITY_REL_POWERPLANT_ID)

GO

CREATE VIEW VW_CITY_BUILDINGS AS (SELECT *
FROM CITY_BUILDINGS
INNER JOIN CITY_BUILDING_TYPES ON CITY_BUILDING_TYPES.CITY_BUILDING_TYPE_ID = CITY_BUILDINGS.BUILDING_TYPE_ID
INNER JOIN CONSTRUCTION_STATUS ON CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_ID = CITY_BUILDINGS.BUILDING_CONSTRUCTION_STATUS_ID
INNER JOIN VW_USER_PROFESSIONAL_CARACTERISTICS ON CITY_BUILDINGS.BUILDING_OWNER_USER_ID = VW_USER_PROFESSIONAL_CARACTERISTICS.USER_ID)

GO

CREATE VIEW VW_CITY_CONSTRUCTION_LOGS AS (SELECT *
FROM CONSTRUCTION_LOGS
INNER JOIN CITY_BUILDINGS ON CONSTRUCTION_LOGS.CONSTRUCTION_BUILDING_ID = CITY_BUILDINGS.BUILDING_ID
INNER JOIN COMPANIES ON COMPANIES.COMPANY_ID = CONSTRUCTION_LOGS.CONSTRUCTION_COMPANY_ID)