--==================================================================================================================================================
--============= CITY_MGMT_VIEWS.sql ================================================================================================================
--============= Aqui são criadas views para a gestão das cidades ===================================================================================
--==================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--VIEW PARA LISTAR TODOS OS DADOS RELATIVOS �S CIDADES
CREATE VIEW VW_CITIES AS (SELECT [CITY_ID]
,CITIES.CITY_NAME
,CITIES.CITY_LOCATION
,CITIES.CITY_BUILT_DATE
,CITY_CONSTRUCTION_STATUS.CITY_CONSTRUCTION_STATUS_NAME
,CITIES.CITY_PRESIDENT_ID,
USER_FIRST_NAME AS PRESIDENT_FIRST_NAME,
USER_LAST_NAME AS PRESIDENT_LAST_NAME,
USER_EMAIL AS PRESIDENT_EMAIL,
USER_PHONENUMBER AS PRESIDENT_PHONENUMBER,
USER_PROFILE_PICTURE_PATH AS PRESIDENT_PROFILE_PICTURE_PATH,
USER_BIRTHDATE AS PRESIDENT_BIRTHDATE,
USER_GENDER_NAME AS PRESIDENT_GENDER,
COUNTRY_NAME AS PRESIDENT_COUNTRY,
USER_JOB_NAME AS PRESIDENT_JOB,
USER_ACADEMIC_LEVEL_NAME AS PRESIDENT_ACADEMIC_LEVEL
FROM CITIES
INNER JOIN VW_USERS_NON_SENSITIVE_INFORMATION ON CITIES.CITY_PRESIDENT_ID = VW_USERS_NON_SENSITIVE_INFORMATION.USER_ID
INNER JOIN CITY_CONSTRUCTION_STATUS ON CITY_CONSTRUCTION_STATUS.CITY_CONSTRUCTION_STATUS_ID = CITIES.CITY_CONSTRUCTION_STATUS_ID)

GO

CREATE VIEW VW_CITIES_BASIC_INFORMATION AS (SELECT [CITY_ID]
,CITIES.CITY_NAME
,CITIES.CITY_LOCATION
,CITIES.CITY_BUILT_DATE
,CITY_CONSTRUCTION_STATUS.CITY_CONSTRUCTION_STATUS_NAME
,CITIES.CITY_PRESIDENT_ID,
USER_FIRST_NAME AS PRESIDENT_FIRST_NAME,
USER_LAST_NAME AS PRESIDENT_LAST_NAME,
USER_EMAIL AS PRESIDENT_EMAIL,
USER_PHONENUMBER AS PRESIDENT_PHONENUMBER,
USER_PROFILE_PICTURE_PATH AS PRESIDENT_PROFILE_PICTURE_PATH
FROM CITIES (NOLOCK)
INNER JOIN VW_USERS_NON_SENSITIVE_INFORMATION ON CITIES.CITY_PRESIDENT_ID = VW_USERS_NON_SENSITIVE_INFORMATION.USER_ID
INNER JOIN CITY_CONSTRUCTION_STATUS ON CITY_CONSTRUCTION_STATUS.CITY_CONSTRUCTION_STATUS_ID = CITIES.CITY_CONSTRUCTION_STATUS_ID)

GO

--VIEW PARA LISTAR OS DADOS ECON�MICOS DAS CIDADES
CREATE VIEW VW_CITIES_ECONOMICAL_DATA AS (SELECT CITY_ECONOMICAL_DATA.CITY_ECONOMICAL_DATA_ID
,CITY_ECONOMICAL_DATA.CITY_ID
,CITY_ECONOMICAL_DATA.CITY_LIFE_COST
,CITY_ECONOMICAL_DATA.CITY_GDP
,CITY_ECONOMICAL_DATA.CITY_AVERAGE_INCOME
,CITIES.CITY_NAME
,CITIES.CITY_LOCATION
,CITIES.CITY_PRESIDENT_ID
,CITIES.CITY_BUILT_DATE
,CITIES.CITY_CONSTRUCTION_STATUS_ID
FROM CITY_ECONOMICAL_DATA
INNER JOIN CITIES ON CITY_ECONOMICAL_DATA.CITY_ID = CITIES.CITY_ID)

GO

--VIEW PARA LISTAR OS DADOS DEMOGR�FICOS DAS CIDADES
CREATE VIEW VW_CITIES_DEMOGRAPHIC_DATA AS (SELECT CITY_DEMOGRAPHICS_DATA.CITY_DEMOGRAPHICS_DATA_ID
,CITY_DEMOGRAPHICS_DATA.CITY_ID
,CITY_DEMOGRAPHICS_DATA.CITY_SURFACE_AREA
,CITY_DEMOGRAPHICS_DATA.CITY_POPULATION
,CITY_DEMOGRAPHICS_DATA.CITY_LIFE_EXPECTANCY
,CITY_DEMOGRAPHICS_DATA.CITY_CRIME_RATE
,CITIES.CITY_NAME
,CITIES.CITY_LOCATION
,CITIES.CITY_PRESIDENT_ID
,CITIES.CITY_BUILT_DATE
,CITIES.CITY_CONSTRUCTION_STATUS_ID
FROM CITY_DEMOGRAPHICS_DATA
INNER JOIN CITIES ON CITY_DEMOGRAPHICS_DATA.CITY_ID = CITIES.CITY_ID)

GO

--VIEW PARA LISTAR OS DADOS AMBIENTAIS DAS CIDADES
CREATE VIEW VW_CITIES_ENVIRONMENTAL_DATA AS (SELECT CITY_ENVIRONMENTAL_DATA.CITY_ENVIRONMENTAL_DATA_ID
,CITY_ENVIRONMENTAL_DATA.CITY_ID
,CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_TEMPERATURE
,CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_HUMIDITY
,CITY_ENVIRONMENTAL_DATA.CITY_OXYGEN_LEVELS
,CITIES.CITY_NAME
,CITIES.CITY_LOCATION
,CITIES.CITY_PRESIDENT_ID
,CITIES.CITY_BUILT_DATE
,CITIES.CITY_CONSTRUCTION_STATUS_ID
FROM CITY_ENVIRONMENTAL_DATA
INNER JOIN CITIES ON CITY_ENVIRONMENTAL_DATA.CITY_ID = CITIES.CITY_ID)

GO

--VIEW PARA LISTAR AS ASSOCIA��ES ENTRE CIDADES E CENTRAIS EL�TRICAS
CREATE VIEW VW_CITIES_REL_POWERPLANTS AS (SELECT CITY_REL_POWERPLANTS.CITY_REL_POWERPLANT_ID
,CITY_REL_POWERPLANTS.CITY_ID
,CITY_REL_POWERPLANTS.CITY_ENERGY_SOURCE_ID
,CITIES.CITY_NAME
,CITIES.CITY_LOCATION
,CITIES.CITY_PRESIDENT_ID
,CITIES.CITY_BUILT_DATE
,CITIES.CITY_CONSTRUCTION_STATUS_ID
,POWER_PLANTS.POWER_PLANT_NAME
,POWER_PLANTS.POWER_PLANT_COMPANY_ID
,POWER_PLANTS.POWER_PLANT_TYPE_ID
,POWER_PLANTS.POWER_PLANT_LOCATION
,POWER_PLANTS.POWER_PLANT_MAX_OUTPUT_CAPACITY
,POWER_PLANTS.POWER_PLANT_STATUS_ID
,POWER_PLANTS.POWER_PLANT_NEXT_MAINTENANCE_DATE
,POWER_PLANTS.POWER_PLANT_INSTALLATION_DATE
FROM CITY_REL_POWERPLANTS
INNER JOIN CITIES ON CITIES.CITY_ID = CITY_REL_POWERPLANTS.CITY_ID
INNER JOIN POWER_PLANTS ON POWER_PLANTS.POWER_PLANT_ID = CITY_REL_POWERPLANTS.CITY_REL_POWERPLANT_ID)

GO

--VIEW PARA LISTAR TODAS AS INFRAESTRUTURAS/CONSTRU��ES REGISTADAS
CREATE VIEW VW_CITY_BUILDINGS AS (SELECT *
FROM CITY_BUILDINGS
INNER JOIN CITY_BUILDING_TYPES ON CITY_BUILDING_TYPES.CITY_BUILDING_TYPE_ID = CITY_BUILDINGS.BUILDING_TYPE_ID
INNER JOIN CONSTRUCTION_STATUS ON CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_ID = CITY_BUILDINGS.BUILDING_CONSTRUCTION_STATUS_ID
INNER JOIN VW_USERS_BASIC_INFORMATION ON CITY_BUILDINGS.BUILDING_OWNER_USER_ID = VW_USERS_BASIC_INFORMATION.USER_ID)

GO

--VIEW PARA LISTAR OS LOGS RELATIVOS AO PROCESSO DE CONSTRU��O DE INFRAESTRUTURAS
CREATE VIEW VW_CITY_CONSTRUCTION_LOGS AS (SELECT *
FROM CONSTRUCTION_LOGS
INNER JOIN CITY_BUILDINGS ON CONSTRUCTION_LOGS.CONSTRUCTION_BUILDING_ID = CITY_BUILDINGS.BUILDING_ID
INNER JOIN COMPANIES ON COMPANIES.COMPANY_ID = CONSTRUCTION_LOGS.CONSTRUCTION_COMPANY_ID)

--VIEW PARA LISTAR O NÚMERO DE PESSOAS POR METRO QUADRADO DE CADA CIDADE.
CREATE VIEW VW_PEOPLE_PER_SQUARE_METER AS (SELECT CITY_NAME, 
(CITY_POPULATION/CITY_SURFACE_AREA) AS PEOPLE_PER_SQUARE_METER
FROM VW_CITIES_DEMOGRAPHIC_DATA (NOLOCK))
GO


--VIEW PARA LISTAR AS CIDADES MENOS SAUDÁVEIS.
CREATE VIEW VW_UNHEALTHY_CITIES AS (SELECT TOP (5) CITIES.CITY_NAME, CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_TEMPERATURE, CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_HUMIDITY FROM CITIES (NOLOCK)
INNER JOIN CITY_ENVIRONMENTAL_DATA (NOLOCK) ON CITIES.CITY_ID = CITY_ENVIRONMENTAL_DATA.CITY_ID
WHERE (CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_TEMPERATURE - 26) > 5
AND (CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_HUMIDITY - 50) > 15);
GO

--VIEW PARA LISTAR AS CIDADES MAIS SAUDÁVEIS.
CREATE VIEW VW_HEALTHY_CITIES AS (SELECT TOP (5) CITIES.CITY_NAME, CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_TEMPERATURE, CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_HUMIDITY FROM CITIES (NOLOCK)
INNER JOIN CITY_ENVIRONMENTAL_DATA (NOLOCK) ON CITIES.CITY_ID = CITY_ENVIRONMENTAL_DATA.CITY_ID
WHERE (CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_TEMPERATURE - 26) <= 5
AND (CITY_ENVIRONMENTAL_DATA.CITY_AVERAGE_HUMIDITY - 50) <= 15);
GO

--VIEW PARA LISTAR AS 5 CIDADES COM MENOR CUSTO DE VIDA.
CREATE VIEW VW_LIFE_COST AS (SELECT TOP (5) VW_CITIES.CITY_NAME, VW_CITIES_ECONOMICAL_DATA.CITY_LIFE_COST, VW_CITIES_ECONOMICAL_DATA.CITY_GDP, VW_CITIES_ECONOMICAL_DATA.CITY_AVERAGE_INCOME 
FROM VW_CITIES (NOLOCK) RIGHT JOIN VW_CITIES_ECONOMICAL_DATA 
(NOLOCK) ON VW_CITIES.CITY_ID = VW_CITIES_ECONOMICAL_DATA.CITY_ID 
WHERE (VW_CITIES_ECONOMICAL_DATA.CITY_AVERAGE_INCOME - VW_CITIES_ECONOMICAL_DATA.CITY_LIFE_COST) > 0);
GO

--VIEW PARA LISTAR O RENDIMENTO DE CADA SISTEMA DE SUPORTE À VIDA DE OXIGÉNIO RELATIVAMENTE À SUA CAPACIDADE MÁXIMA DE PRODUÇÃO.
CREATE VIEW PERFORMANCE_OF_OXIGEN_PRODUCTION AS (SELECT LOG_ID, (CAST(ROUND(CAST(LOG_OXIGEN_OUTPUT AS FLOAT) / CAST(LIFE_SUPPORT_SYSTEMS.SYSTEM_MAX_OUTPUT_CAPACITY AS FLOAT)*100, 2) AS VARCHAR) + ' %') AS OXIGEN_OUTPUT_RATE
FROM OXIGEN_PRODUCTION_LOGS (NOLOCK) INNER JOIN LIFE_SUPPORT_SYSTEMS (NOLOCK) ON OXIGEN_PRODUCTION_LOGS.LOG_SOURCE_ID = LIFE_SUPPORT_SYSTEMS.SYSTEM_ID);
GO

--VIEW PARA LISTAR O RENDIMENTO DE CADA SISTEMA DE SUPORTE À VIDA DE ÁGUA RELATIVAMENTE À SUA CAPACIDADE MÁXIMA DE PRODUÇÃO.
CREATE VIEW PERFORMANCE_OF_WATER_EXTRACTION AS (SELECT LOG_ID, (CAST(ROUND(CAST(LOG_WATER_OUTPUT AS FLOAT) / CAST(LIFE_SUPPORT_SYSTEMS.SYSTEM_MAX_OUTPUT_CAPACITY AS FLOAT)*100, 2) AS VARCHAR) + ' %') AS WATER_OUTPUT_RATE
FROM WATER_EXTRACTION_LOGS (NOLOCK) INNER JOIN LIFE_SUPPORT_SYSTEMS (NOLOCK) ON WATER_EXTRACTION_LOGS.LOG_SOURCE_ID = LIFE_SUPPORT_SYSTEMS.SYSTEM_ID);
GO