--==================================================================================================================================================
--============= POWER_MGMT_VIEWS.sql ===============================================================================================================
--============= Aqui são criadas views para a obtenção de estatisticas da produção e distribuição de energia. ======================================
--==================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

CREATE VIEW VW_SPACE_LOGISTICS AS (SELECT [MISSION_ID]
,SPACE_LOGISTICS.OPERATION_ID
,[MISSION_NAME]
,[MISSION_TYPE_ID]
,[MISSION_COMPANY_ID]
,[MISSION_TRANSPORT_VEHICLE_ID]
,[DESCRIPTION]
,[LAUNCH_DATE]
,[LANDING_DATE]
,[LAUNCH_LOCATION]
,[LANDING_LOCATION]
,[BUDGET]
,COMPANIES.COMPANY_NAME
,COMPANIES.COMPANY_TYPE_ID
,COMPANIES.COMPANY_COUNTRY_ID
,COMPANIES.COMPANY_CEO_ID
,COMPANIES.COMPANY_CAPITAL
,VEHICLES.VEHICLE_SERIAL_NUMBER
,VEHICLES.VEHICLE_MANUFACTURER_ID
,VEHICLES.VEHICLE_PRODUCTION_DATE
,VEHICLES.VEHICLE_NAME
,VEHICLES.VEHICLE_TYPE_ID
,VEHICLES.VEHICLE_MASS
,VEHICLES.VEHICLE_LENGTH
,VEHICLES.VEHICLE_WIDTH
,VEHICLES.VEHICLE_HEIGHT
,VEHICLES.VEHICLE_FUEL_TYPE_ID
,VEHICLES.VEHICLE_NEXT_MAINTENANCE_DATE
,OPERATION_LOGS.OPERATION_NAME
,OPERATION_LOGS.OPERATION_TIMESTAMP
,OPERATION_LOGS.OPERATION_CATEGORY_ID
,OPERATION_LOGS.OPERATION_STATUS_ID
,LOGISTICS_OPERATION_TYPE.OPERATION_TYPE_NAME
FROM SPACE_LOGISTICS
INNER JOIN COMPANIES ON COMPANIES.COMPANY_ID = SPACE_LOGISTICS.MISSION_COMPANY_ID
INNER JOIN VEHICLES ON VEHICLES.VEHICLE_ID = SPACE_LOGISTICS.MISSION_TRANSPORT_VEHICLE_ID
INNER JOIN OPERATION_LOGS ON OPERATION_LOGS.OPERATION_ID = SPACE_LOGISTICS.OPERATION_ID
INNER JOIN LOGISTICS_OPERATION_TYPE ON LOGISTICS_OPERATION_TYPE.OPERATION_TYPE_ID = SPACE_LOGISTICS.MISSION_TYPE_ID)