--==================================================================================================================================================
--============= POWER_MGMT_VIEWS.sql ===============================================================================================================
--============= Aqui são criadas views para a obtenção de estatisticas da produção e distribuição de energia. ======================================
--==================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--ESTA VIEW CONCENTRA OS DADOS DE CADA CENTRAL ELETRICA;
CREATE VIEW VW_POWER_PLANTS AS (SELECT POWER_PLANT_NAME,
COMPANIES.COMPANY_NAME,
POWER_PLANT_TYPE.POWER_PLANT_TYPE_NAME,
POWER_PLANT_LOCATION,
POWER_PLANT_MAX_OUTPUT_CAPACITY,
POWER_PLANT_INSTALLATION_DATE,
MACHINE_STATUS_NAME,
POWER_PLANTS.POWER_PLANT_NEXT_MAINTENANCE_DATE
FROM POWER_PLANTS (NOLOCK)
INNER JOIN MACHINE_STATUS ON POWER_PLANTS.POWER_PLANT_STATUS_ID = MACHINE_STATUS.MACHINE_STATUS_ID
INNER JOIN COMPANIES ON COMPANIES.COMPANY_ID = POWER_PLANTS.POWER_PLANT_COMPANY_ID
INNER JOIN POWER_PLANT_TYPE ON POWER_PLANT_TYPE.POWER_PLANT_TYPE_ID = POWER_PLANTS.POWER_PLANT_TYPE_ID)
GO

--ESTA VIEW CONCENTRA OS DADOS DE CADA CENTRAL ELETRICA;
CREATE VIEW VW_STORAGE_DEVICES AS (SELECT TOP (1000) [POWER_STORAGE_DEVICE_ID]
,POWER_PLANTS.POWER_PLANT_NAME
,COMPANIES.COMPANY_NAME
,POWER_STORAGE_DEVICES.POWER_STORAGE_DEVICE_NAME
,POWER_STORAGE_DEVICES.POWER_STORAGE_DEVICE_MAX_CAPACITY
,MACHINE_STATUS.MACHINE_STATUS_NAME
FROM [_MORPHEUS_ENGINE_].[dbo].[POWER_STORAGE_DEVICES] (NOLOCK)
INNER JOIN MACHINE_STATUS ON POWER_STORAGE_DEVICES.POWER_STORAGE_DEVICE_STATUS_ID = MACHINE_STATUS.MACHINE_STATUS_ID
INNER JOIN COMPANIES ON POWER_STORAGE_DEVICES.POWER_STORAGE_DEVICE_MANUFACTURER_ID = COMPANIES.COMPANY_ID
INNER JOIN POWER_PLANTS ON POWER_PLANTS.POWER_PLANT_ID = POWER_STORAGE_DEVICES.POWER_PLANT_ID)
GO

--ESTA VIEW LISTA OS PRIMEIROS 1000 LOGS RELATIVOS Á PRODUÇÃO DE ENERGIA
CREATE VIEW VW_POWER_FLUX_LOGS_TOP1000 AS (SELECT TOP(1000)
POWER_FLUX_LOGS.LOG_ID,
POWER_FLUX_LOGS.LOG_TIME,
POWER_PLANTS.POWER_PLANT_NAME,
POWER_FLUX_LOGS.LOG_POWER_OUTPUT,
POWER_FLUX_LOGS.LOG_POWER_CONSUMPTION,
POWER_FLUX_LOGS.LOG_POWER_STORAGE
FROM POWER_FLUX_LOGS (NOLOCK)
INNER JOIN POWER_PLANTS ON POWER_FLUX_LOGS.LOG_SOURCE_ID = POWER_PLANTS.POWER_PLANT_STATUS_ID)
GO