--==================================================================================================================================
--============= USER_VIEWS.sql =====================================================================================================
--============= Aqui são criadas views para a obtenção de dados do utilizador. =====================================================
--==================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--ESTA VIEW LISTA A INFORMAÇÃO COMPLETA DOS UTILIZADORES
CREATE VIEW VW_USERS_FULL_INFORMATION AS (SELECT USER_ID,
USER_FIRST_NAME,
 USER_LAST_NAME,
 USER_PASSWORD_HASH,
 USER_EMAIL,
 USER_PHONENUMBER,
 USER_PROFILE_PICTURE_PATH,
 USER_REGISTRATION_TIMESTAMP,
 USER_BIRTHDATE,
 USER_GENDERS.USER_GENDER_NAME,
 COUNTRIES.COUNTRY_NAME,
 COUNTRIES.COUNTRY_CAPITAL_CITY,
 USER_ADRESS,
 USER_CITIZEN_CARD_NUMBER,
 USER_SALARY,
 USER_BANK_ACCOUNT_NUMBER,
 USER_ACADEMIC_LEVEL.USER_ACADEMIC_LEVEL_ID,
 USER_ACADEMIC_LEVEL.USER_ACADEMIC_LEVEL_NAME,
 USER_JOBS.USER_JOB_NAME,
 USER_LEVEL.USER_LEVEL_NAME
 FROM USERS (NOLOCK)
 INNER JOIN USER_GENDERS ON USER_GENDERS.USER_GENDER_ID = USERS.USER_GENDER_ID 
 INNER JOIN COUNTRIES ON USERS.USER_COUNTRY_ID = COUNTRIES.COUNTRY_ID
 INNER JOIN USER_ACADEMIC_LEVEL ON USER_ACADEMIC_LEVEL.USER_ACADEMIC_LEVEL_ID = USERS.USER_ACADEMIC_LEVEL_ID
 INNER JOIN USER_JOBS ON USER_JOBS.USER_JOB_ID = USERS.USER_JOB_ID
 INNER JOIN USER_LEVEL ON USERS.USER_LEVEL_ID = USER_LEVEL.USER_LEVEL_ID);

 GO

 --ESTA VIEW LISTA DADOS NÃO SENSIVEIS DOS UTILIZADORES
CREATE VIEW VW_USERS_NON_SENSITIVE_INFORMATION AS (SELECT USER_ID,
USER_FIRST_NAME,
 USER_LAST_NAME,
 USER_EMAIL,
 USER_PHONENUMBER,
 USER_PROFILE_PICTURE_PATH,
 USER_BIRTHDATE,
 USER_GENDERS.USER_GENDER_NAME,
 COUNTRIES.COUNTRY_NAME,
 COUNTRIES.COUNTRY_CAPITAL_CITY,
 USER_ADRESS,
 USER_ACADEMIC_LEVEL.USER_ACADEMIC_LEVEL_ID,
 USER_ACADEMIC_LEVEL.USER_ACADEMIC_LEVEL_NAME,
 USER_JOBS.USER_JOB_NAME,
 USER_LEVEL.USER_LEVEL_NAME
 FROM USERS (NOLOCK)
 INNER JOIN USER_GENDERS ON USER_GENDERS.USER_GENDER_ID = USERS.USER_GENDER_ID 
 INNER JOIN COUNTRIES ON USERS.USER_COUNTRY_ID = COUNTRIES.COUNTRY_ID
 INNER JOIN USER_ACADEMIC_LEVEL ON USER_ACADEMIC_LEVEL.USER_ACADEMIC_LEVEL_ID = USERS.USER_ACADEMIC_LEVEL_ID
 INNER JOIN USER_JOBS ON USER_JOBS.USER_JOB_ID = USERS.USER_JOB_ID
 INNER JOIN USER_LEVEL ON USERS.USER_LEVEL_ID = USER_LEVEL.USER_LEVEL_ID);

 GO

--ESTA VIEW LISTA A INFORMAÇÃO BASICA DOS UTILIZADORES
CREATE VIEW VW_USERS_BASIC_INFORMATION AS (SELECT USER_ID,
USER_FIRST_NAME,
 USER_LAST_NAME,
 USER_EMAIL,
 USER_PHONENUMBER,
 USER_PROFILE_PICTURE_PATH,
 USER_BIRTHDATE,
 USER_GENDERS.USER_GENDER_NAME,
 COUNTRIES.COUNTRY_NAME,
 USER_JOBS.USER_JOB_NAME
 FROM USERS (NOLOCK)
 INNER JOIN USER_GENDERS ON USER_GENDERS.USER_GENDER_ID = USERS.USER_GENDER_ID 
 INNER JOIN COUNTRIES ON USERS.USER_COUNTRY_ID = COUNTRIES.COUNTRY_ID
 INNER JOIN USER_ACADEMIC_LEVEL ON USER_ACADEMIC_LEVEL.USER_ACADEMIC_LEVEL_ID = USERS.USER_ACADEMIC_LEVEL_ID
 INNER JOIN USER_JOBS ON USER_JOBS.USER_JOB_ID = USERS.USER_JOB_ID
 INNER JOIN USER_LEVEL ON USERS.USER_LEVEL_ID = USER_LEVEL.USER_LEVEL_ID);