--==================================================================================================================================================
--============= VEHICLES&SPACECRAFT_VIEWS.sql ======================================================================================================
--============= Aqui são criadas views para a obtenção de dados de máquinas e veículos, espaciais, terrestres, aquáticos e aérios. =================
--==================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--ESTA VIEW CONCENTRA OS DADOS DE CADA VEÍCULO;
CREATE VIEW VW_SCIENTIFIC_PROSPECTION_DATA AS (SELECT TASK_ID,
TASK_TIMESTAMP,
TASK_LOCATION,
TASK_RAW_DATA,
VEHICLES.VEHICLE_SERIAL_NUMBER,
VEHICLES.VEHICLE_NAME,
VEHICLE_TYPES.VEHICLE_TYPE_NAME,
SCIENTIFIC_TASK_TYPES.TASK_TYPE_NAME,
TASK_EVENTS.TASK_EVENT_NAME
FROM SCIENTIFIC_PROSPECTION_LOGS (NOLOCK)
INNER JOIN VEHICLES ON VEHICLES.VEHICLE_ID = SCIENTIFIC_PROSPECTION_LOGS.TASK_DEVICE_ID 
INNER JOIN VEHICLE_TYPES ON VEHICLE_TYPES.VEHICLE_TYPE_ID = VEHICLES.VEHICLE_TYPE_ID
INNER JOIN TASK_EVENTS ON TASK_EVENTS.TASK_EVENT_ID = SCIENTIFIC_PROSPECTION_LOGS.TASK_EVENT_ID
INNER JOIN SCIENTIFIC_TASK_TYPES ON SCIENTIFIC_TASK_TYPES.TASK_TYPE_NAME = SCIENTIFIC_PROSPECTION_LOGS.TASK_TYPE_ID);
GO

--ESTA VIEW CONCENTRA OS DADOES DOS VEICULOS (ESPACIAIS, TERRESTRES, AEREOS, SUBAQUATICOS, ...)
CREATE VIEW VW_VEHICLES AS (SELECT VEHICLES.VEHICLE_SERIAL_NUMBER,
COMPANIES.COMPANY_NAME,
VEHICLES.VEHICLE_PRODUCTION_DATE,
VEHICLES.VEHICLE_NAME,
VEHICLE_TYPES.VEHICLE_TYPE_NAME,
VEHICLES.VEHICLE_MASS,
VEHICLES.VEHICLE_LENGTH,
VEHICLES.VEHICLE_HEIGHT,
VEHICLE_FUEL_TYPES.VEHICLE_FUEL_TYPE_NAME,
VEHICLES.VEHICLE_NEXT_MAINTENANCE_DATE
FROM VEHICLES
INNER JOIN COMPANIES ON COMPANIES.COMPANY_ID = VEHICLES.VEHICLE_ID
INNER JOIN VEHICLE_TYPES ON VEHICLE_TYPES.VEHICLE_TYPE_ID = VEHICLES.VEHICLE_TYPE_ID
INNER JOIN VEHICLE_FUEL_TYPES ON VEHICLES.VEHICLE_FUEL_TYPE_ID = VEHICLE_FUEL_TYPES.VEHICLE_FUEL_TYPE_ID)
GO