USE [_MORPHEUS_ENGINE_]
GO

CREATE VIEW VW_USER_PROFESSIONAL_CARACTERISTICS AS (SELECT USER_ID,
USER_FIRST_NAME,
 USER_LAST_NAME,
 USER_PASSWORD_HASH,
 USER_EMAIL,
 USER_PHONENUMBER,
 USER_PROFILE_PICTURE_PATH,
 USER_REGISTRATION_TIMESTAMP,
 USER_BIRTHDATE,
 USER_GENDERS.USER_GENDER_NAME,
 COUNTRIES.COUNTRY_NAME,
 COUNTRIES.COUNTRY_CAPITAL_CITY,
 USER_ADRESS,
 USER_CITIZEN_CARD_NUMBER,
 USER_SALARY,
 USER_BANK_ACCOUNT_NUMBER,
 USER_ACADEMIC_LEVEL.USER_ACADEMIC_LEVEL_NAME,
 USER_JOBS.USER_JOB_NAME,
 USER_LEVEL.USER_LEVEL_NAME
 FROM USERS (NOLOCK)
 INNER JOIN USER_GENDERS ON USER_GENDERS.USER_GENDER_ID = USERS.USER_GENDER_ID 
 INNER JOIN COUNTRIES ON USERS.USER_COUNTRY_ID = COUNTRIES.COUNTRY_ID
 INNER JOIN USER_ACADEMIC_LEVEL ON USER_ACADEMIC_LEVEL.USER_ACADEMIC_LEVEL_ID = USERS.USER_ACADEMIC_LEVEL_ID
 INNER JOIN USER_JOBS ON USER_JOBS.USER_JOB_ID = USERS.USER_JOB_ID
 INNER JOIN USER_LEVEL ON USERS.USER_LEVEL_ID = USER_LEVEL.USER_LEVEL_ID);

GO

 SELECT * FROM VW_USER_PROFESSIONAL_CARACTERISTICS;
/*
 CREATE VIEW VW_SCIENTIFIC_PROSPECTION_DATA AS SELECT 
*/