--==================================================================================================================
--============= USER_QUERIES.sql ===================================================================================
--============= Contem queries para listagem e analise estatistica de dados inerentes ás empresas ==================
--==================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--region LIFE_SUPPORT_SYSTEMS

CREATE PROCEDURE SP_INSERT_LIFE_SUPPORT_SYSTEM_LINK_CITY
    @LSS_ID INT,
    @CITY_ID INT
AS
BEGIN
    IF((SELECT COUNT(*) FROM CITIES WHERE CITY_ID = @CITY_ID) > 0)
    BEGIN
        INSERT INTO CITY_REL_LIFE_SUPPORT_SYSTEMS (CITY_ID, CITY_LIFE_SUPPORT_SYSTEM_ID)
        VALUES (
            @CITY_ID, -- ID da cidade onde o sistema de suporte de vida está localizado
            @LSS_ID -- ID do sistema de suporte de vida
        );
    END
    ELSE
    BEGIN
        PRINT 'A cidade especificada n��o existe.';
    END 
END

GO

CREATE PROCEDURE SP_INSERT_LIFE_SUPPORT_SYSTEM
    @LSS_NAME VARCHAR(50),
    @LSS_TYPE_ID INT,
    @LSS_COMPANY_ID INT,
    @LSS_LOCATION VARCHAR(100),
    @LSS_STATUS_ID INT,
    @LSS_MAX_OUTPUT_CAPACITY FLOAT,
    @LSS_INSTALLATION_DATE DATE,
    @LSS__NEXT_MAINTENANCE_DATE DATE,
    @LSS_CITY_ID INT

AS
BEGIN
    INSERT INTO LIFE_SUPPORT_SYSTEMS (
        SYSTEM_NAME,
        SYSTEM_TYPE_ID,
        SYSTEM_COMPANY_ID,
        SYSTEM_LOCATION,
        SYSTEM_STATUS_ID,
        SYSTEM_MAX_OUTPUT_CAPACITY,
        SYSTEM_INSTALLATION_DATE,
        SYSTEM_NEXT_MAINTENANCE_DATE
    ) VALUES (
        @LSS_NAME,
        @LSS_TYPE_ID,
        @LSS_COMPANY_ID,
        @LSS_LOCATION,
        @LSS_STATUS_ID,
        @LSS_MAX_OUTPUT_CAPACITY,
        @LSS_INSTALLATION_DATE,
        @LSS__NEXT_MAINTENANCE_DATE
    );

    DECLARE @LAST_LSS_ID INT = SCOPE_IDENTITY();

    EXEC SP_INSERT_LIFE_SUPPORT_SYSTEM_LINK_CITY
    @LSS_ID = @LAST_LSS_ID,
    @CITY_ID = @LSS_CITY_ID;
END

GO

--PROCEDURE PARA INSERIR UM REGISTO DE MANUTEN����O DE UM SISTEMA DE SUPORTE DE VIDA (LIFE SUPPORT SYSTEM - LSS)
CREATE PROCEDURE SP_INSERT_LSS_MAINTENANCE_LOG
@SYSTEM_ID INT,
@MAINTENANCE_DESCRIPTION VARCHAR(MAX),
@MAINTENANCE_DATE DATE,
@MAINTENANCE_TECHNITIAN_ID INT,
@MAINTENANCE_RESULTS_INFO VARBINARY(MAX),
@NEXT_MAINTENANCE_DATE DATE
AS
BEGIN
	IF((SELECT COUNT(*) FROM LIFE_SUPPORT_SYSTEMS WHERE SYSTEM_ID = @SYSTEM_ID) > 0)
	BEGIN
		INSERT INTO POWER_PLANT_MAINTENANCE_LOGS (
			POWER_PLANT_ID,
			MAINTENANCE_DESCRIPTION,
			MAINTENANCE_DATE,
			MAINTENANCE_TECHNITIAN_ID,
			MAINTENANCE_RESULTS_INFO
		) VALUES (
			@SYSTEM_ID,
			@MAINTENANCE_DESCRIPTION,
			@MAINTENANCE_DATE,
			@MAINTENANCE_TECHNITIAN_ID,
			@MAINTENANCE_RESULTS_INFO
		);

		DECLARE @COUNT_LSS_MAINTENANCE_LOGS INT;
		SET @COUNT_LSS_MAINTENANCE_LOGS = (SELECT COUNT(*) FROM LIFE_SUPPORT_SYSTEM_MAINTENANCE_LOGS WHERE SYSTEM_ID = @SYSTEM_ID);

		INSERT INTO OPERATION_LOGS (
			OPERATION_NAME,
			OPERATION_CATEGORY_ID,
			OPERATION_STATUS_ID
		) VALUES (
			'SP_LSS_MAINT-' + (SELECT SYSTEM_NAME FROM LIFE_SUPPORT_SYSTEMS WHERE SYSTEM_ID = @SYSTEM_ID) + '_' + @COUNT_LSS_MAINTENANCE_LOGS,
			2, -- CATEGORIA DE MANUTEN����O
			1  -- ESTADO 'COMPLETO (COMPLETED)'
		);

		UPDATE LIFE_SUPPORT_SYSTEMS
			SET SYSTEM_NEXT_MAINTENANCE_DATE = @NEXT_MAINTENANCE_DATE
			WHERE SYSTEM_ID = @SYSTEM_ID;
	END
	ELSE
	BEGIN
		PRINT 'A central el�trica n��o existe.';
	END
END

--endregion LIFE_SUPPORT_SYSTEMS