--=============================================================================================================================================================================================
--============= DATA_INSERTION_PROCEDURES.sql =================================================================================================================================================
--============= Cont�m SP's utilizadas na insers�o de dados em diversas tabelas (insers�es que envolvam mais que uma tabela em simult�neo), por parte do utilizador. ==========================
--=============================================================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--region POWER_PLANTS

--PROCEDURE PARA INSERS�O DE CENTRAL EL�TRICA NA TABELA 'POWER_PLANTS'. DURANTE ESSA INSERS�O, ESTA � TAMB�M ASSOCIADA �(S) CIDADE(S) ALIMENTADA(S) POR SI
CREATE PROCEDURE SP_INSERT_POWER_PLANTS
@POWER_PLANT_NAME varchar(50),
@POWER_PLANT_COMPANY_ID int,
@POWER_PLANT_TYPE_ID int,
@POWER_PLANT_LOCATION varchar(100),
@POWER_PLANT_MAX_OUTPUT_CAPACITY float,
@POWER_PLANT_STATUS_ID int,
@POWER_PLANT_NEXT_MAINTENANCE_DATE date,
@POWER_PLANT_INSTALLATION_DATE date,
@TARGET_CITIES_ID varchar(20)
AS
BEGIN
	--=======================================================================================================================================================================================================================
	--INSERS�O DA CENTRAL EL�TRICA NA TABELA POWER_PLANTS
	INSERT INTO POWER_PLANTS(POWER_PLANT_NAME, POWER_PLANT_COMPANY_ID, POWER_PLANT_TYPE_ID, POWER_PLANT_LOCATION, POWER_PLANT_MAX_OUTPUT_CAPACITY, POWER_PLANT_STATUS_ID, POWER_PLANT_NEXT_MAINTENANCE_DATE, POWER_PLANT_INSTALLATION_DATE) VALUES(
	@POWER_PLANT_NAME,
	@POWER_PLANT_COMPANY_ID,
	@POWER_PLANT_TYPE_ID,
	@POWER_PLANT_LOCATION,
	@POWER_PLANT_MAX_OUTPUT_CAPACITY,
	@POWER_PLANT_STATUS_ID,
	@POWER_PLANT_NEXT_MAINTENANCE_DATE,
	@POWER_PLANT_INSTALLATION_DATE)

	--=======================================================================================================================================================================================================================

	DECLARE @_POWER_PLANT_ID INT; --ID DA CENTRAL EL�TRICA INSERIDA
	SET @_POWER_PLANT_ID = (SELECT MAX(POWER_PLANT_ID) FROM POWER_PLANTS) --A CENTRAL INSERIDA VAI TER O MAIOR ID DA TABELA (� A MAIS RECENTE)

	DECLARE @TARGET_CITIES_TEMP_TABLE TABLE(splited_str varchar(4)) --TABELA TEMPORARIA PARA GUARDAR OS ID's DAS CIDADES A CONECTAR � CENTRAL
	INSERT INTO @TARGET_CITIES_TEMP_TABLE(splited_str)	(SELECT [value] FROM STRING_SPLIT(@TARGET_CITIES_ID, ',')); --CONVERS�O DE VARCHAR(20) PARA TABLE (SPLIT DA STRING)

	DECLARE @I INT = 1; -- CONTADOR PARA CICLO WHILE
	WHILE @I-1 < (SELECT COUNT(*) FROM @TARGET_CITIES_TEMP_TABLE) -- ESTE CICLO VAI PERCORRER TODOS OS VALORES DA TABELA @TARGET_CITIES_TEMP_TABLE, ENQUANTO @I-1 FOR MENOR QUE O N�MERO DE REGISTOS DESTA
	BEGIN
		DECLARE @_CITY_ID INT; --ID DA CIDADE A LIGAR � CENTRAL EL�TRICA
		SET @_CITY_ID = (SELECT TOP(1) CONVERT(INT, splited_str) FROM @TARGET_CITIES_TEMP_TABLE WHERE @I = CONVERT(INT, splited_str))

		INSERT INTO CITY_REL_POWERPLANTS(CITY_ID, CITY_ENERGY_SOURCE_ID) VALUES(@_CITY_ID, @_POWER_PLANT_ID) --INSERS�O DA LIGA��O DA CIDADE COM A CENTRAL EL�TRICA, NA TABELA QUE AS RELACIONA (CITY_REL_POWERPLANTS)
		SET @I = @I + 1 --INCREMENTO DO CONTADOR @I
	END
	--=======================================================================================================================================================================================================================
END
/*EXEMPLO DE EXECU��O:
EXEC SP_INSERT_POWER_PLANTS @POWER_PLANT_NAME = 'AAAAA',
@POWER_PLANT_COMPANY_ID = 1,
@POWER_PLANT_TYPE_ID = 1,
@POWER_PLANT_LOCATION = 'LOCATION3301',
@POWER_PLANT_MAX_OUTPUT_CAPACITY = 20000,
@POWER_PLANT_STATUS_ID = 1,
@POWER_PLANT_NEXT_MAINTENANCE_DATE = '1990-09-09',
@POWER_PLANT_INSTALLATION_DATE = '1990-09-09',
@TARGET_CITIES_ID = '1,2,3'
*/

GO

--PROCEDURE PARA INSERIR UM NOVO DISPOSITIVO DE ARMAZENAMENTO DE ENERGIA
CREATE PROCEDURE SP_INSERT_POWER_PLANT_STORAGE_DEVICE
@POWER_PLANT_ID INT,
@POWER_STORAGE_DEVICE_MANUFACTURER_ID INT,
@POWER_STORAGE_DEVICE_NAME VARCHAR(50),
@POWER_STORAGE_DEVICE_MAX_CAPACITY FLOAT,
@POWER_STORAGE_DEVICE_STATUS_ID INT
AS
BEGIN
	IF((SELECT COUNT(*)
		FROM POWER_PLANTS
		WHERE POWER_PLANT_ID = @POWER_PLANT_ID) > 0)
	BEGIN
		IF((SELECT COUNT(*)
			FROM POWER_STORAGE_DEVICES
			WHERE POWER_STORAGE_DEVICE_NAME = @POWER_STORAGE_DEVICE_NAME) > 0)
		BEGIN
			PRINT 'O dispositivo de armazenamento de energia já existe.';
		END
		ELSE
		BEGIN
			IF((SELECT COUNT(*) FROM COMPANIES WHERE COMPANY_ID = @POWER_STORAGE_DEVICE_MANUFACTURER_ID) = 0)
			BEGIN
				PRINT 'O fabricante do dispositivo de armazenamento de energia n��o existe.';
				
			END
			ELSE
			BEGIN
				INSERT INTO POWER_STORAGE_DEVICES (
					POWER_PLANT_ID,
					POWER_STORAGE_DEVICE_MANUFACTURER_ID,
					POWER_STORAGE_DEVICE_NAME,
					POWER_STORAGE_DEVICE_MAX_CAPACITY,
					POWER_STORAGE_DEVICE_STATUS_ID
				) VALUES (
					@POWER_PLANT_ID,
					@POWER_STORAGE_DEVICE_MANUFACTURER_ID,
					@POWER_STORAGE_DEVICE_NAME,
					@POWER_STORAGE_DEVICE_MAX_CAPACITY,
					@POWER_STORAGE_DEVICE_STATUS_ID
				);
			END
		END	
	END
	ELSE
	BEGIN
		PRINT 'A central el�trica n��o existe.';
	END
END

GO

--PROCEDURE PARA INSERIR UM REGISTO DE MANUTEN����O DE UMA CENTRAL EL�TRICA
CREATE PROCEDURE SP_INSERT_POWER_PLANT_MAINTENANCE_LOG
@POWER_PLANT_ID INT,
@MAINTENANCE_DESCRIPTION VARCHAR(MAX),
@MAINTENANCE_DATE DATE,
@MAINTENANCE_TECHNITIAN_ID INT,
@MAINTENANCE_RESULTS_INFO VARBINARY(MAX),
@NEXT_MAINTENANCE_DATE DATE
AS
BEGIN
	IF((SELECT COUNT(*) FROM POWER_PLANTS WHERE POWER_PLANT_ID = @POWER_PLANT_ID) > 0)
	BEGIN
		INSERT INTO POWER_PLANT_MAINTENANCE_LOGS (
			POWER_PLANT_ID,
			MAINTENANCE_DESCRIPTION,
			MAINTENANCE_DATE,
			MAINTENANCE_TECHNITIAN_ID,
			MAINTENANCE_RESULTS_INFO
		) VALUES (
			@POWER_PLANT_ID,
			@MAINTENANCE_DESCRIPTION,
			@MAINTENANCE_DATE,
			@MAINTENANCE_TECHNITIAN_ID,
			@MAINTENANCE_RESULTS_INFO
		);

		DECLARE @COUNT_POWER_PLANT_MAINTENANCE_LOGS INT;
		SET @COUNT_POWER_PLANT_MAINTENANCE_LOGS = (SELECT COUNT(*) FROM POWER_PLANT_MAINTENANCE_LOGS WHERE POWER_PLANT_ID = @POWER_PLANT_ID);

		INSERT INTO OPERATION_LOGS (
			OPERATION_NAME,
			OPERATION_CATEGORY_ID,
			OPERATION_STATUS_ID
		) VALUES (
			'SP_POWERP_MAINT-' + (SELECT POWER_PLANT_NAME FROM POWER_PLANTS WHERE POWER_PLANT_ID = @POWER_PLANT_ID) + '_' + @COUNT_POWER_PLANT_MAINTENANCE_LOGS,
			2, -- CATEGORIA DE MANUTEN����O
			1  -- ESTADO 'COMPLETO (COMPLETED)'
		);

		UPDATE POWER_PLANTS
			SET POWER_PLANT_NEXT_MAINTENANCE_DATE = @NEXT_MAINTENANCE_DATE
			WHERE POWER_PLANT_ID = @POWER_PLANT_ID;
	END
	ELSE
	BEGIN
		PRINT 'A central el�trica n��o existe.';
	END
END

--endregion POWER_PLANTS