--=============================================================================================================================================================================================
--============= DATA_INSERTION_PROCEDURES.sql =================================================================================================================================================
--============= Cont�m SP's utilizadas na insers�o de dados em diversas tabelas (insers�es que envolvam mais que uma tabela em simult�neo), por parte do utilizador. ==========================
--=============================================================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--#region SPACE_LOGISTICS

--STORED PROCEDURE PARA A INSERS�O DE MISS�ES ESPACIAIS LOGISTICAS NA TABELA 'SPACE_LOGISTICS'
CREATE PROCEDURE SP_INSERT_SPACE_LOGISTICS
@MISSION_NAME varchar(100),
@MISSION_TYPE_ID int,
@MISSION_COMPANY_ID int,
@MISSION_TRANSPORT_VEHICLE_ID int,
@DESCRIPTION text,
@LAUNCH_DATE date,
@LANDING_DATE date,
@LAUNCH_LOCATION varchar(50),
@LANDING_LOCATION varchar(50),
@BUDGET float
AS
BEGIN
	INSERT INTO OPERATION_LOGS(OPERATION_NAME, OPERATION_CATEGORY_ID, OPERATION_STATUS_ID) VALUES('SP_LG-' + @MISSION_NAME, 1, 1) --INSERS�O DA OPERA��O A QUE ESTA MISS�O EST� ASSOCIADA (REFERENCIA NA TABELA OPERATION_LOGS)
	DECLARE @LAST_OPERATION_ID INT;
	SET	@LAST_OPERATION_ID = (SELECT MAX(OPERATION_LOGS.OPERATION_ID) FROM OPERATION_LOGS);

	--INSERS�O DA MISS�O NA TABELA SPACE_LOGISTICS
	INSERT INTO SPACE_LOGISTICS(OPERATION_ID, MISSION_NAME, MISSION_TYPE_ID, MISSION_COMPANY_ID, MISSION_TRANSPORT_VEHICLE_ID, DESCRIPTION, LAUNCH_DATE, LANDING_DATE, LAUNCH_LOCATION, LANDING_LOCATION, BUDGET) VALUES(@LAST_OPERATION_ID,
	@MISSION_NAME,
	@MISSION_TYPE_ID,
	@MISSION_COMPANY_ID,
	@MISSION_TRANSPORT_VEHICLE_ID,
	@DESCRIPTION,
	@LAUNCH_DATE,
	@LANDING_DATE,
	@LAUNCH_LOCATION,
	@LANDING_LOCATION,
	@BUDGET)
END

--#endregion SPACE_LOGISTICS

GO

--#region VEHICLES

--STORED PROCEDURE PARA INSERS�O DE VE�CULOS, NA TABELA 'VEHICLES'
CREATE PROCEDURE SP_INSERT_VEHICLES
@VEHICLE_SERIAL_NUMBER varchar(50),
@VEHICLE_MANUFACTURER_ID int,
@VEHICLE_PRODUCTION_DATE date,
@VEHICLE_NAME varchar(100),
@VEHICLE_TYPE_ID int,
@VEHICLE_MASS float,
@VEHICLE_LENGTH float,
@VEHICLE_WIDTH float,
@VEHICLE_HEIGHT float,
@VEHICLE_FUEL_TYPE_ID int,
@VEHICLE_NEXT_MAINTENANCE_DATE date
AS
BEGIN
	--INSERS�O DO VE�CULO, NA TABELA 'VEHICLES'
	INSERT INTO VEHICLES(VEHICLE_SERIAL_NUMBER, VEHICLE_MANUFACTURER_ID, VEHICLE_PRODUCTION_DATE, VEHICLE_NAME, VEHICLE_TYPE_ID, VEHICLE_MASS, VEHICLE_LENGTH, VEHICLE_WIDTH, VEHICLE_HEIGHT, VEHICLE_FUEL_TYPE_ID, VEHICLE_NEXT_MAINTENANCE_DATE) VALUES (
	@VEHICLE_SERIAL_NUMBER,
	@VEHICLE_MANUFACTURER_ID,
	@VEHICLE_PRODUCTION_DATE,
	@VEHICLE_NAME,
	@VEHICLE_TYPE_ID,
	@VEHICLE_MASS,
	@VEHICLE_LENGTH,
	@VEHICLE_WIDTH,
	@VEHICLE_HEIGHT,
	@VEHICLE_FUEL_TYPE_ID,
	@VEHICLE_NEXT_MAINTENANCE_DATE);
END

--#endregion VEHICLES