--==================================================================================================================================
--============= ENERGY_MGMT_FUNCTIONS.sql ==========================================================================================
--============= Contém funções bastante uteis na obtenção de estatisticas relativamente á gestão e produção de energia.=============
--==================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

CREATE PROCEDURE SP_INSERT_SPACE_LOGISTICS
@MISSION_NAME varchar(100),
@MISSION_TYPE_ID int,
@MISSION_COMPANY_ID int,
@MISSION_TRANSPORT_VEHICLE_ID int,
@DESCRIPTION text,
@LAUNCH_DATE date,
@LANDING_DATE date,
@LAUNCH_LOCATION varchar(50),
@LANDING_LOCATION varchar(50),
@BUDGET float
AS
BEGIN
	INSERT INTO OPERATION_LOGS(OPERATION_NAME, OPERATION_CATEGORY_ID, OPERATION_STATUS_ID) VALUES('SP_LG-' + @MISSION_NAME, 1, 1)
	DECLARE @LAST_OPERATION_ID INT;
	SET	@TMP = (SELECT MAX(LOG_ID) FROM OPERATION_LOGS);

	INSERT INTO SPACE_LOGISTICS(OPERATION_ID, MISSION_NAME, MISSION_TYPE_ID, MISSION_COMPANY_ID, MISSION_TRANSPORT_VEHICLE_ID, DESCRIPTION, LAUNCH_DATE, LANDING_DATE, LAUNCH_LOCATION, LANDING_LOCATION, BUDGET) VALUES(@TMP,
	@MISSION_NAME,
	@MISSION_TYPE_ID,
	@MISSION_COMPANY_ID,
	@MISSION_TRANSPORT_VEHICLE_ID,
	@DESCRIPTION,
	@LAUNCH_DATE,
	@LANDING_DATE,
	@LAUNCH_LOCATION,
	@LANDING_LOCATION,
	BUDGET)
END

GO

CREATE PROCEDURE SP_INSERT_VEHICLES
@VEHICLE_SERIAL_NUMBER varchar(50),
@VEHICLE_MANUFACTURER_ID int,
@VEHICLE_PRODUCTION_DATE date,
@VEHICLE_NAME varchar(100),
@VEHICLE_TYPE_ID int,
@VEHICLE_MASS float,
@VEHICLE_LENGTH float,
@VEHICLE_WIDTH float,
@VEHICLE_HEIGHT float,
@VEHICLE_FUEL_TYPE_ID int,
@VEHICLE_NEXT_MAINTENANCE_DATE date
AS
BEGIN
	INSERT INTO VEHICLES(VEHICLE_SERIAL_NUMBER, VEHICLE_MANUFACTURER_ID, VEHICLE_PRODUCTION_DATE, VEHICLE_NAME, VEHICLE_TYPE_ID, VEHICLE_MASS, VEHICLE_LENGTH, VEHICLE_WIDTH, VEHICLE_HEIGHT, VEHICLE_FUEL_TYPE_ID, VEHICLE_NEXT_MAINTENANCE_DATE) VALUES (
	@VEHICLE_SERIAL_NUMBER,
	@VEHICLE_MANUFACTURER_ID,
	@VEHICLE_PRODUCTION_DATE,
	@VEHICLE_NAME,
	@VEHICLE_TYPE_ID,
	@VEHICLE_MASS,
	@VEHICLE_LENGTH,
	@VEHICLE_WIDTH,
	@VEGICLE_HEIGHT,
	@VEHICLE_FUEL_TYPE_ID,
	@VEHICLE_NEXT_MAINTENANCE_DATE);
END

GO

CREATE PROCEDURE SP_INSERT_POWER_PLANTS
@POWER_PLANT_NAME varchar(50),
@POWER_PLANT_COMPANY_ID int,
@POWER_PLANT_TYPE_ID int,
@POWER_PLANT_LOCATION varchar(100),
@POWER_PLANT_MAX_OUTPUT_CAPACITY float,
@POWER_PLANT_STATUS_ID int,
@POWER_PLANT_NEXT_MAINTENANCE_DATE date,
@POWER_PLANT_INSTALLATION_DATE date,
@TARGET_CITIES varchar(20)
AS
BEGIN
	INSERT INTO POWER_PLANTS(POWER_PLANT_NAME, POWER_PLANT_COMPANY_ID, POWER_PLANT_TYPE_ID, POWER_PLANT_LOCATION, POWER_PLANT_MAX_OUTPUT_CAPACITY, POWER_PLANT_STATUS_ID, POWER_PLANT_NEXT_MAINTENANCE_DATE, POWER_PLANT_INSTALLATION_DATE) VALUES(
	@POWER_PLANT_NAME,
	@POWER_PLANT_COMPANY_ID,
	@POWER_PLANT_TYPE_ID,
	@POWER_PLANT_LOCATION,
	@POWER_PLANT_MAX_OUTPUT_CAPACITY,
	@POWER_PLANT_STATUS_ID,
	@POWER_PLANT_NEXT_MAINTENANCE_DATE,
	@POWER_PLANT_INSTALLATION_DATE)
END