--=============================================================================================================================================================================================
--============= DATA_QUERY_PROCEDURES.sql =====================================================================================================================================================
--============= Cont�m SP's utilizadas na insers�o de dados em diversas tabelas (insers�es que envolvam mais que uma tabela em simult�neo), por parte do utilizador. =======================
--=============================================================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

CREATE PROCEDURE SP_FILTER_COMPANY_BY_TYPE
@COMPANY_TYPE_NAME VARCHAR(20)
AS
BEGIN
    SELECT COMPANY_TYPE_NAME,
        COMPANY_ID,
        COMPANY_NAME,
        COMPANY_COUNTRY_ID,
        COUNTRY_NAME,
        COMPANY_CEO_ID,
        USER_FIRST_NAME,
        USER_LAST_NAME,
        COMPANY_CAPITAL
    FROM VW_COMPANY_DATA (NOLOCK)
    WHERE COMPANY_TYPE_NAME = @COMPANY_TYPE_NAME
END
GO

CREATE PROCEDURE SP_FILTER_USERS_BY_COMPANY
@COMPANY_NAME VARCHAR(100)
AS
BEGIN
    SELECT VW_COMPANY_DATA.COMPANY_NAME,
    VW_USERS_FULL_INFORMATION.USER_ID,
        VW_USERS_FULL_INFORMATION.USER_FIRST_NAME,
        VW_USERS_FULL_INFORMATION.USER_LAST_NAME,
        VW_USERS_FULL_INFORMATION.USER_EMAIL,
        VW_USERS_FULL_INFORMATION.USER_PHONENUMBER,
        VW_USERS_FULL_INFORMATION.USER_PROFILE_PICTURE_PATH,
        VW_USERS_FULL_INFORMATION.USER_BIRTHDATE,
        VW_USERS_FULL_INFORMATION.USER_GENDER_NAME,
        VW_USERS_FULL_INFORMATION.COUNTRY_NAME AS USER_COUNTRY,
        VW_USERS_FULL_INFORMATION.USER_JOB_NAME,
        VW_USERS_FULL_INFORMATION.USER_SALARY,
        VW_COMPANY_DATA.COMPANY_TYPE_NAME,
        VW_COMPANY_DATA.COUNTRY_NAME AS COMPANY_COUNTRY,
        VW_COMPANY_DATA.USER_FIRST_NAME + ' ' + VW_COMPANY_DATA.USER_LAST_NAME AS COMPANY_CEO_FULL_NAME,
        VW_COMPANY_DATA.COMPANY_CAPITAL FROM USER_REL_COMPANY (NOLOCK)
    INNER JOIN VW_COMPANY_DATA (NOLOCK) ON VW_COMPANY_DATA.COMPANY_ID = USER_REL_COMPANY.USER_COMPANY_ID
    INNER JOIN VW_USERS_FULL_INFORMATION ON VW_USERS_FULL_INFORMATION.USER_ID = USER_REL_COMPANY.USER_ID
    WHERE VW_COMPANY_DATA.COMPANY_NAME = @COMPANY_NAME
END
GO

CREATE PROCEDURE SP_CALC_AVERAGE_SALARIES_BY_JOB_AND_COMPANY
@COMPANY_NAME VARCHAR(100),
@JOB_NAME VARCHAR(75)
AS 
BEGIN
    IF(@JOB_NAME = 'ALL')
        SELECT VW_COMPANY_DATA.COMPANY_NAME, AVG(VW_USERS_FULL_INFORMATION.USER_SALARY) AS AVERAGE_SALARY FROM USER_REL_COMPANY (NOLOCK)
        INNER JOIN VW_COMPANY_DATA (NOLOCK) ON VW_COMPANY_DATA.COMPANY_ID = USER_REL_COMPANY.USER_COMPANY_ID
        INNER JOIN VW_USERS_FULL_INFORMATION ON VW_USERS_FULL_INFORMATION.USER_ID = USER_REL_COMPANY.USER_ID
        GROUP BY VW_COMPANY_DATA.COMPANY_NAME
        HAVING VW_COMPANY_DATA.COMPANY_NAME = @COMPANY_NAME;
    ELSE
        SELECT VW_COMPANY_DATA.COMPANY_NAME, AVG(VW_USERS_FULL_INFORMATION.USER_SALARY) AS AVERAGE_SALARY FROM USER_REL_COMPANY (NOLOCK)
        INNER JOIN VW_COMPANY_DATA (NOLOCK) ON VW_COMPANY_DATA.COMPANY_ID = USER_REL_COMPANY.USER_COMPANY_ID
        INNER JOIN VW_USERS_FULL_INFORMATION ON VW_USERS_FULL_INFORMATION.USER_ID = USER_REL_COMPANY.USER_ID
        WHERE VW_USERS_FULL_INFORMATION.USER_JOB_NAME = @JOB_NAME
        GROUP BY VW_COMPANY_DATA.COMPANY_NAME
        HAVING VW_COMPANY_DATA.COMPANY_NAME = @COMPANY_NAME;
END
GO

CREATE PROCEDURE SP_FILTER_COMPANIES_BY_COUNTRY
@COUNTRY_NAME VARCHAR(75)
AS
BEGIN
    SELECT VW_COMPANY_DATA.COUNTRY_NAME,
        COMPANY_ID,
        COMPANY_NAME,
        COMPANY_TYPE_NAME,
        COMPANY_COUNTRY_ID,
        COMPANY_CEO_ID,
        USER_FIRST_NAME,
        USER_LAST_NAME,
        COMPANY_CAPITAL
    FROM VW_COMPANY_DATA (NOLOCK)
    WHERE VW_COMPANY_DATA.COUNTRY_NAME = @COUNTRY_NAME
END

GO

--PROCEDURE PARA LISTAR OS UTILIZADORES COM UMA DETERMINADA PROFISSÃO, DE UMA DETERMINADA EMPRESA (OPCIONAL).
CREATE PROCEDURE SP_LIST_COMPANY_USERS_BY_JOB
@JOB_NAME VARCHAR(75), @COMPANY_NAME VARCHAR(100)
AS
BEGIN
    IF(@COMPANY_NAME != '')
    BEGIN
        SELECT USER_JOB_NAME, EMPLOYER_COMPANY_NAME,
        USER_ID,
        USER_FIRST_NAME + ' ' + USER_LAST_NAME AS USER_FULL_NAME,
        USER_EMAIL,
        USER_PHONENUMBER,
        USER_PROFILE_PICTURE_PATH,
        USER_BIRTHDATE,
        USER_GENDER_NAME,
        COUNTRY_NAME,
        USER_ADRESS,
        USER_ACADEMIC_LEVEL_NAME,
        USER_LEVEL_NAME
        FROM VW_USERS_NON_SENSITIVE_INFORMATION (NOLOCK)
        WHERE USER_JOB_NAME = @JOB_NAME AND @COMPANY_NAME = EMPLOYER_COMPANY_NAME
    END
    ELSE
    BEGIN
        SELECT USER_JOB_NAME, EMPLOYER_COMPANY_NAME,
        USER_ID,
        USER_FIRST_NAME + ' ' + USER_LAST_NAME AS USER_FULL_NAME,
        USER_EMAIL,
        USER_PHONENUMBER,
        USER_PROFILE_PICTURE_PATH,
        USER_BIRTHDATE,
        USER_GENDER_NAME,
        COUNTRY_NAME,
        USER_ADRESS,
        USER_ACADEMIC_LEVEL_NAME,
        USER_LEVEL_NAME
        FROM VW_USERS_NON_SENSITIVE_INFORMATION (NOLOCK)
        WHERE USER_JOB_NAME = @JOB_NAME
    END
END

GO

CREATE PROCEDURE SP_COUNT_USERS_BY_COMPANY
@COMPANY_NAME VARCHAR(100)
AS
BEGIN
    SELECT COUNT(*) AS TOTAL_USERS
    FROM VW_USERS_BASIC_INFORMATION (NOLOCK)
    WHERE @COMPANY_NAME = EMPLOYER_COMPANY_NAME
END